require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const unitsRaw = `301	ADM CENTRAL	ADM CENTRAL
160	ALFENAS	RODOVIARIO
1400	CAPELINHA	RODOVIARIO
159	CARGAS E ENCOMENDAS	CARGAS E ENCOMENDAS
162	CASSIA	RODOVIARIO
2799	CEL FABRICIANO	VALE DO AÇO
3600	DUVAL DE BARROS	DUVAL DE BARROS
158	EXPEDICAO	EXPEDIÇÃO
800	GUANHAES	RODOVIARIO
163	GUAXUPE	RODOVIARIO
157	INDUSTRIA	INDÚSTRIA
900	IPATINGA	VALE DO AÇO
1100	ITABIRA	RODOVIARIO
173	ITAJUBA	RODOVIARIO
3500	ITAUNA	ITAUNA
300	JARDIM MONTANHES	RODOVIARIO
2600	LAGOA DA PRA	RODOVIARIO
116	LAGOA SANTA	LAGOA SANTA
2900	LAVRAS	LAVRAS
165	LAVRAS ST RT	RODOVIARIO
1901	MARINGÁ	PARANÁ
1200	MONTES CLARO	MONTES CLARO
121	NEVES MUNICIPAL	NEVES MUNICIPAL
4100	NOVA LIMA	NOVA LIMA
1000	OLIVEIRA	RODOVIARIO
167	PASSOS	RODOVIARIO
169	POUSO ALEGRE	RODOVIARIO
168	POÇOS DE CAL	RODOVIARIO
175	RODOVIARIO	RODOVIARIO
155	SAO MARCOS	SAO MARCOS
2800	TIMOTEO	VALE DO AÇO
4200	VARGINHA	VARGINHA
2700	VESPASIANO	VESPASIANO`;

const rolesRaw = `3522	ENC LANTERN II	ENC LANTERN II
3519	ENC DE AGENCIA	ENC DE AGENCIA
3518	ENC ALMOX II	ENC ALMOX II
3517	EMISSOR DE FRETE	EMISSOR DE FRETE
3516	ELETRICISTA IV	ELETRICISTA IV
3515	ELETRICISTA III	ELETRICISTA III
3513	ELETRICISTA I	ELETRICISTA I
3512	ELETR PREDIAL	ELETR PREDIAL
3510	COORDENADOR MONI	COORDENADOR MONI
3509	COORDENADOR DE T	COORDENADOR DE TI
3508	COORD MONIT I	COORD MONIT I
3507	COORD MANUT I	COORD MANUT I
3506	CONTROLADOR DE M	CONTROLADOR DE M
3504	CONF ENCOMENDAS	CONF ENCOMENDAS
3503	COBRADOR	COBRADOR
3502	CAPOTEIRO III	CAPOTEIRO III
3501	BORRACHEIRO V	BORRACHEIRO V
3499	BORRACHEIRO II	BORRACHEIRO II
3497	BORRAC III	BORRAC III
3496	BILHETEIRO URBAN	BILHETEIRO URBAN
3493	AUXILIAR DE VIAG	AUXILIAR DE VIAG
3491	AUXILIAR DE TRAF	AUXILIAR DE TRAF
3490	AUXILIAR DE TESO	AUXILIAR DE TESO
3489	AUXILIAR DE MOLE	AUXILIAR DE MOLE
3488	AUXILIAR DE MECA	AUXILIAR DE MECA
3487	AUXILIAR DE LANT	AUXILIAR DE LANT
3486	AUXILIAR DE ELET	AUXILIAR DE ELET
3485	AUXILIAR DE CARG	AUXILIAR DE CARG
3483	AUXILIAR DE ALMO	AUXILIAR DE ALMO
3482	AUXILIAR CONTAB	AUXILIAR CONTAB
3479	AUX TESOU I	AUX TESOU I
3478	AUX MONIT	AUX MONIT
3477	AUX EXPED	AUX EXPED
3473	AUX DE MONIT II	AUX DE MONIT II
3470	TORNEIRO MEC IV	TORNEIRO MEC IV
3469	TECNICO DE SEGUR	TECNICO DE SEGUR
3468	TEC SEG TRAB V	TEC SEG TRAB V
3466	TEC SEG TRAB IV	TEC SEG TRAB IV
3464	TEC SEG TRAB II	TEC SEG TRAB II
3461	SUPERVISOR MANUT	SUPERVISOR MANUT
3460	ASS TESOURARIA	ASS TESOURARIA
3459	ASSISTENTE ADMIN	ASSISTENTE ADMIN
3457	SERVENTE PEDREIR	SERVENTE PEDREIR
3455	ASS VENDAS V	ASS VENDAS V
3454	RECEPCIONISTA	RECEPCIONISTA
3453	ASS VENDAS II	ASS VENDAS II
3452	ASS VENDAS	ASS VENDAS
3449	PINTOR LETRISTA	PINTOR LETRISTA
3448	PINTOR IV	PINTOR IV
3447	PINTOR III	PINTOR III
3446	ASS PESSOAL II	ASS PESSOAL II
3445	PINTOR I	PINTOR I
3441	ASS OPER I	ASS OPER I
3438	MOTORI MICRO	MOTORI MICRO
3436	ASS ADM II	ASS ADM II
3435	ARRUMADOR	ARRUMADOR
3430	MECANICO IV	MECANICO IV
3429	MECANICO II	MECANICO II
3426	MEC MONTA	MEC MONTA
3425	ANALISTA ADM II	ANALISTA ADM II
3422	LUBRIFICADOR	LUBRIFICADOR
3421	LANTERNEIRO V	LANTERNEIRO V
3420	ANA TESOURARIA I	ANA TESOURARIA I
3419	LANTERNEIRO IV	LANTERNEIRO IV
3418	ALMOXARIFE IV	ALMOXARIFE IV
3417	ALMOXARIFE III	ALMOXARIFE III
3415	ALMOXARIFE II	ALMOXARIFE II
3414	ALMOXARIFE I	ALMOXARIFE I
3413	LANTERNEIRO III	LANTERNEIRO III
3410	LANTERNEIRO II	LANTERNEIRO II
3409	AGENT DE ESTACAO	AGENT DE ESTACAO
3408	LANTERNEIRO I	LANTERNEIRO I
3407	ADVOGADO SENIOR	ADVOGADO SENIOR
3406	LANTERNEIRO A	LANTERNEIRO A
3405	ADVOGADO PL III	ADVOGADO PL III
3404	ADVOGADO JR III	ADVOGADO JR III
3403	ADVOGADO JR II	ADVOGADO JR II
3402	ADV JUNIOR	ADV JUNIOR
3401	GER DA QUALIDADE	GER DA QUALIDADE
3400	ENGENHEIRO DE SE	ENGENHEIRO DE SE
3399	ENCARREGADO SERV	ENCARREGADO SERV
3397	ENCARREGADO DE T	ENCARREGADO DE T
3396	ENCARREGADO DE E	ENCARREGADO DE E
4186	AUX TEC SEG TRAB	AUX TEC SEG TRAB IV
4185	ASSIST RH IV	ASSIST RH IV
4183	COORD CONTABILID	COORDENADOR (A) CONTABILIDADE
4180	ASSIST PESSOAL I	ASSIST PESSOAL I
4179	AUX BORRAC I	AUX BORRACHARIA I
4178	ENC GARAGEM I	ENC GARAGEM I
4175	ENC MANUT II	ENC MANUT II
4173	GESTOR ADM	GESTOR ADM
4172	COORD TRAFEGO II	COORD TRAFEGO II
4171	COORD TRAFEGO I	COORD TRAFEGO I
4170	ENC LANTERN A	ENC LANTERN A
4169	ENC ELETRICA I	ENC ELETRICA I
4168	COOR MANUT II	COOR MANUT II
4167	TESOUREIRO I	TESOUREIRO I
4166	ENC TESOURARIA	ENC TESOURARIA
4165	GERENTE DE CUSTO	GERENTE DE CUSTO
4164	GER FINANCEIRO	GER FINANCEIRO
4163	COORD RH II	COORD RH II
4162	COORD PESS II	COORD PESS II
4161	AUX SERV MED II	AUX SERVICOS MEDICOS II
4160	AUX RH II	AUX RH II
4159	ASSIST TES III	ASSISTENTE TESOURARIA III
4158	ASSIST RH I	ASSIST RH I
4157	ANAL PROJETO IV	ANAL PROJETO IV
4155	AUX ADM IV	AUX ADM IV
4154	COORD TRAF I	COORD TRAF I
4153	AUX CONT MANUT	AUX CONTROLADOR MANUTENCAO
4152	TESOUREIRO II	TESOUREIRO II
4151	TESOUREIRO I	TESOUREIRO I
4150	FISCAL URBANO	FISCAL URBANO
4149	SOLDADOR III	SOLDADOR III
4148	ENC MANUT I	ENCARREGADO MANUTENCAO I
4147	CONTR MAN II	CONTROLADOR MANUTENCAO II
4146	AUX ELETRICA I	AUX ELETRICA I
4145	TESOUREIRO IV	TESOUREIRO IV
4144	TESOUREIRO III	TESOUREIRO III
4143	TEC SEG TRAB III	TEC SEGURANCA TRABALHO III
4142	AUX BILHETAGEM I	AUX BILHETAGEM I
4139	BILHETEIRO LIDER	BILHETEIRO LIDER
4138	ENC TRAFEGO I	ENC TRAFEGO I
4137	AUX ADM III	AUX ADM III
4136	TOR MECANICO III	TORNEIRO MECANICO III
4135	TEC ELETRICA V	TEC ELETRICA V
4134	TEC ELETRICA IV	TEC ELETRICA IV
4133	SERV PEDREIRO A	SERVENTE PEDREIRO A
4132	PINTOR LETR IV	PINTOR LETRISTA IV
4131	MOLEIRO I	MOLEIRO I
4130	MEC IND IV	MECANICO INDUSTRIAL IV
4129	MEC PNEUMAT II	MEC PNEUMATICO II
4128	MEC MONTADOR III	MEC MONTADOR III
4127	MEC MONTADOR II	MEC MONTADOR II
4126	ENC LANTER I	ENC LANTERNAGEM I
4125	ENC ELETRICA A	ENC ELETRICA A
4124	ENC BORRAC I	ENCARREGADO BORRACHARIA I
4123	ENC ALMOXARIF I	ENCARREGADO ALMOXARIFADO I
4122	ELETRICISTA I	ELETRICISTA I
4121	BORRACHEIRO IV	BORRACHEIRO IV
4120	AUX PINTURA	AUX PINTURA
4118	AUX CAPOTEIRO	AUX CAPOTEIRO
4117	AUX BORRACHARIA	AUX BORRACHARIA
4116	AUX BORR I	AUX BORRACHARIA I
4115	AUX ALMOXARIFADO	AUX ALMOXARIFADO
4114	AUX ALMOX I	AUXILIAR ALMOXARIFE I
4113	AUD MANUT I	AUDITOR MANUTENCAO I
4112	TEC ENF TRAB I	TEC ENFERMAGEM DO TRABALHO I ANALISTA
4108	AUX TESOUR V	AUX TESOUR V
4093	AUX TESOU IV	AUX TESOU IV
4092	MOT INSTRUTOR	MOT INSTRUTOR
4091	ANALISTA ADM II	ANALISTA ADM II
4090	ASS VENDAS II	ASS VENDAS II
4089	TEC SEG TRAB II	TEC SEG TRAB II
4087	ASS TESOU IV	ASS TESOU IV
4086	BILHETEIRO URBAN	BILHETEIRO URBAN
4085	ENC LANTERN II	ENC LANTERN II
4084	ENC ELETRICA II	ENC ELETRICA II
4083	MOTORISTA URB	MOTORISTA URB
4082	GER UNIDADE	GER UNIDADE
4081	ALMOXARIFADO IV	ALMOXARIFADO IV
4080	ENC SERV GER I	ENC SERV GER I
4079	AUX MECANICA	AUX MECANICA
4078	PINTOR I	PINTOR I
4077	AUX MONITORAMENT	AUX MONITORAMENT
4076	CONTR MANUT III	CONTR MANUT III
4075	MOTORI MICRO	MOTORI MICRO
4074	BORRAC III	BORRAC III
4073	ASS ADM II	ASS ADM II
4072	TEC SEG TRAB I	TEC SEG TRAB I
4071	LANTERNEIRO III	LANTERNEIRO III
4070	PINTOR IV	PINTOR IV
4069	LUBRIFICADOR	LUBRIFICADOR
4068	PINTOR III	PINTOR III
4067	RECEPCIONISTA	RECEPCIONISTA
4066	AUX ADM II	AUX ADM II
4065	MANOBRISTA	MANOBRISTA
4063	PORTEIRO	PORTEIRO
4062	ALMOXARIFE III	ALMOXARIFE III
4061	AUX TRAFEGO I	AUX TRAFEGO I
4060	FRENTISTA	FRENTISTA
4059	COBRADOR	COBRADOR
4058	MOTORISTA URB	MOTORISTA URB
4057	PINTOR LETR III	PINTOR LETR III
4056	PEDREIRO	PEDREIRO
4055	AUX MOLEIRO	AUX MOLEIRO
4054	MECANICO IV	MECANICO IV
4053	LANTERNEIRO I	LANTERNEIRO I
4052	MECANICO III	MECANICO III
4051	FISCAL	FISCAL
4050	BORRAC I	BORRAC I
4049	LANTERNEIRO II	LANTERNEIRO II
4048	MECANICO I	MECANICO I
4047	ELET IV	ELET IV
4046	BILHETEIRO	BILHETEIRO
4045	ASS ADM I	ASS ADM I
3968	ENG SEG TRAB	ENG SEG TRAB
3967	ADVOGADO SR	ADVOGADO SR
3966	TEC SEG TRAB I	TEC SEG TRAB I
3727	CO PILOTO DE AER	CO PILOTO DE AERONAVES
3726	COMANDANTE DE AE	COMANDANTE DE AERONAVE
3725	AUX USINAGEM	AUX USINAGEM
3720	MOT INSTRUTOR	MOTORISTA INSTRUTOR
3719	AUX DE TRAFEGO I	AUX DE TRAFEGO I
3718	ASSISTENTE BIL I	ASSISTENTE BILHETAGEM I
3717	COORD MAN II	COORDENADOR DE MANUTENCAO  II
3716	ANALI CONTROL V	ANALI CONTROL V
3715	AUX BILHETAG V	AUX BILHETAG V
3714	MED EXAMINADOR	MED EXAMINADOR
3713	AUX PESSOAL IV	AUX PESSOAL IV
3712	ANALIS CUSTO III	ANALIS CUSTO III
3711	ALMOXARIFE	ALMOXARIFE
3710	ENC MANOBRISTA I	ENC MANOBRISTA I
3709	MEC INJECAO II	MEC INJECAO II
3708	MEC INJECAO IV	MEC INJECAO IV
3707	CAPOTEIRO II	CAPOTEIRO II
3706	ENC CAPOTARIA I	ENC CAPOTARIA I
3702	SUPERVISOR TRAFE	SUPERVISOR TRAFEGO III
3701	DESPACHANTE	DESPACHANTE
3700	SECRETARIA	SECRETARIA
3698	COZINHEIRA	COZINHEIRA
3697	COORDENADOR TI	COORDENADOR TI
3696	COORD JURIDICO A	COORD JURIDICO ADMINISTRATIVO
3695	COORDENADOR DE C	COORDENADOR DE CUSTOS
3694	COORDENADOR COMP	COORDENADOR COMPRAS
3693	AUXILIAR JURIDIC	AUXILIAR JURIDICO IV
3692	AUXILIAR JURIDIC	AUXILIAR JURIDICO V
3691	AUXILIAR FINANCE	AUXILIAR FINANCEIRO
3690	AUXILIAR FINANCE	AUXILIAR FINANCEIRO V
3689	AUXILIAR FATURAM	AUXILIAR FATURAMENTO IV
3682	AUXILIAR CONTABI	AUXILIAR CONTABILIDADE II
3681	ASSISTENTE PESSO	ASSISTENTE PESSOAL V
3680	ASSISTENTE JURID	ASSISTENTE JURIDICO I
3679	ASSISTENTE JURID	ASSISTENTE JURIDICO III
3678	ASSISTENTE COMPR	ASSISTENTE COMPRAS II
3677	ASSIST CONTABIL	ASSIST CONTABIL IV
3676	ASSISTENTE CONTA	ASSISTENTE CONTABIL V
3675	ASSISTENTE CONFE	ASSISTENTE CONFERENCIA III
3674	ANALISTA TESOURA	ANALISTA TESOURARIA II
3673	ANALISTA SINISTR	ANALISTA SINISTRO I
3672	ANALISTA PESSOAL	ANALISTA PESSOAL II
3671	ANALISTA JURIDIC	ANALISTA JURIDICO III
3670	ANALISTA EXPEDIÇ	ANALISTA EXPEDIÇAO V
3669	ANALISTA DE FATU	ANALISTA DE FATURAMENTO III
3668	ANALISTA CONTABI	ANALISTA CONTABIL III
3666	ZELADOR	ZELADOR
3664	CONTR MANUT I	CONTR MANUT I
3660	ARRUMADOR	ARRUMADOR
3655	ENC FATURAMENTO	ENC FATURAMENTO
3654	SERV EXTERNOS	SERV EXTERNOS
3653	AUX SERV MED	AUX SERV MED
3652	TEC ENF TRAB II	TEC ENF TRAB II
3648	BILHETEIRO	BILHETEIRO
3647	COORD BILHETERIA	COORD BILHETERIA
3646	EMISSOR DE FRETE	EMISSOR DE FRETE
3644	ANA TESOU III	ANALISTA TESOURARIA III
3643	MOLEIRO V	MOLEIRO V
3642	ENCARREGADO DE M	ENCARREGADO DE MANUTENCAO III
3641	ENCARREGADO ELET	ENCARREGADO ELETRICA A
3640	CAPOTEIRO I	CAPOTEIRO I
3639	AUX LANTERNAGEM	AUX LANTERNAGEM I
3638	PEDREIRO A	PEDREIRO A
3637	MOLEIRO II	MOLEIRO II
3636	MECANICO V	MECANICO V
3635	LANTERNEIRO V	LANTERNEIRO V
3634	ELETRICISTA TACO	ELETRICISTA TACOGRAFISTA I
3633	BORRACHEIRO V	BORRACHEIRO V
3632	AUXILIAR DE MECA	AUXILIAR DE MECANICA I
3631	AUXILIAR DE MOLE	AUXILIAR DE MOLEIRO I
3630	AUXILIAR DE LANT	AUXILIAR DE LANTERNAGEM I
3629	AUXILIAR DE CAPO	AUXILIAR DE CAPOTEIRO I
3628	AUX CONTROLADOR	AUX CONTROLADOR MANUT I
3627	GERENTE DE MANUT	GERENTE DE MANUTENCAO
3626	ENCARREGADO MANU	ENCARREGADO MANUTENCAO I
3625	ENCARREGADO DE L	ENCARREGADO DE LANTERNAGEM A
3624	COORDENADOR DE M	COORDENADOR DE MANUTENCAO III
3623	CONTROLADOR DE M	CONTROLADOR DE MANUTENCAO II
3622	TORNEIRO MECANIC	TORNEIRO MECANICO III
3621	TECNICO ELETRONI	TECNICO ELETRONICA IV
3620	TECNICO ELETRONI	TECNICO ELETRONICA V
3619	PINTOR V	PINTOR V
3618	PINTOR LETRISTA	PINTOR LETRISTA III
3617	SERVENTE PEDREIR	SERVENTE PEDREIRO A
3616	MONTADOR RADIADO	MONTADOR RADIADOR III
3615	MOLEIRO III	MOLEIRO III
3614	MOLEIRO I	MOLEIRO I
3613	MECANICO V	MECANICO V
3612	MECANICO PNEUMAT	MECANICO PNEUMATICO II
3611	MECANICO PNEUMAT	MECANICO PNEUMATICO IV
3610	MECANICO PNEUMAT	MECANICO PNEUMATICO III
3609	MECANICO MONTADO	MECANICO MONTADOR III
3608	MECANICO MONTADO	MECANICO MONTADOR II
3607	MECANICO INDUSTR	MECANICO INDUSTRIAL III
3606	MECANICO INDUSTR	MECANICO INDUSTRIAL II
3605	LANTERNEIRO IV	LANTERNEIRO IV
3604	LANTERNEIRO I	LANTERNEIRO I
3603	ENCARREGADO ELET	ENCARREGADO ELETRICA II
3602	ENCARREGADO DE E	ENCARREGADO DE ELETRICA A
3601	ENCARREGADO DE B	ENCARREGADO DE BORRACHARIA I
3600	ENCARREGADO DE A	ENCARREGADO DE ALMOXARIFADO I
3599	CAPOTEIRO IV	CAPOTEIRO IV
3598	BORRACHEIRO I	BORRACHEIRO I
3597	AUXILIAR DE PINT	AUXILIAR DE PINTURA
3596	AUXILIAR DE MECA	AUXILIAR DE MECANICA
3595	AUXILIAR DE ELET	AUXILIAR DE ELETRICA
3594	AUXILIAR DE CARG	AUXILIAR DE CARGAS
3593	AUXILIAR DE BORR	AUXILIAR DE BORRACHARIA
3592	AUXILIAR ALMOXAR	AUXILIAR ALMOXARIFADO I
3591	AUXILIAR ALMOXAR	AUXILIAR ALMOXARIFADO
3590	AUDITOR DE MANUT	AUDITOR DE MANUTENCAO I
3589	ALMOXARIFE II	ALMOXARIFE II
3588	ALMOXARIFE I	ALMOXARIFE I
3587	TORNEIRO MECANIC	TORNEIRO MECANICO I
3586	SUPERVISOR MANUT	SUPERVISOR MANUTENCAO I
3585	SOLDADOR IV	SOLDADOR IV
3584	SERVICOS GERAIS	SERVICOS GERAIS
3583	SERVENTE DE PEDR	SERVENTE DE PEDREIRO
3582	PORTEIRO	PORTEIRO
3581	PINTOR IV	PINTOR IV
3580	PINTOR III	PINTOR III
3579	PINTOR II	PINTOR II
3578	PEDREIRO	PEDREIRO
3577	MOLEIRO IV	MOLEIRO IV
3576	MECANICO IV	MECANICO IV
3575	MECANICO III	MECANICO III
3573	MECANICO I	MECANICO I
3572	MECANICO A	MECANICO A
3571	MANOBRISTA	MANOBRISTA
3570	LUBRIFICADOR	LUBRIFICADOR
3569	LANTERNEIRO III	LANTERNEIRO III
3568	ENCARREGADO SERV	ENCARREGADO SERVICOS GERAIS I
3567	ENCARREGADO MANU	ENCARREGADO MANUTENCAO II
3566	ENCARREGADO DE L	ENCARREGADO DE LANTERNAGEM I
3565	ENCARREGADO DE E	ENCARREGADO DE ELETRICA I
3564	ENCARREGADO GARA	ENCARREGADO GARAGEM I
3563	ELETRICISTA V	ELETRICISTA V
3562	ELETRICISTA IV	ELETRICISTA IV
3561	ELETRICISTA III	ELETRICISTA III
3560	ELETRICISTA II	ELETRICISTA II
3559	ELETRICISTA I	ELETRICISTA I
3558	CONTROLADOR DE M	CONTROLADOR DE MANUTENCAO III
3557	BORRACHEIRO IV	BORRACHEIRO IV
3556	BORRACHEIRO II	BORRACHEIRO II
3555	AUXILIAR DE PINT	AUXILIAR DE PINTURA I
3554	AUXILIAR DE LANT	AUXILIAR DE LANTERNAGEM
3553	AUXILIAR DE ELET	AUXILIAR DE ELETRICA
3552	AUXILIAR DE ELET	AUXILIAR DE ELETRICA I
3551	AUXILIAR DE CAPO	AUXILIAR DE CAPOTEIRO
3550	TECNICO SEGURANC	TECNICO SEGURANCA TRABALHO III
3549	TECNICO SEGURANC	TECNICO SEGURANCA DO TRABALHO
3546	GERENTE DE UNIDA	GERENTE DE UNIDADE
3545	ENGENHEIRO DE SE	ENGENHEIRO DE SEGURANCA DO TRABALHO
3544	AUX ADMINISTRATI	AUX ADMINISTRATIVO I
3543	AUX ADM V	AUX ADM V
3542	ASSISTENTE TI V	ASSISTENTE TI V
3541	ASSISTENTE TESOU	ASSISTENTE TESOURARIA I
3540	ASSISTENTE TESOU	ASSISTENTE TESOURARIA IV
3539	ASSISTENTE DE BI	ASSISTENTE DE BILHETAGEM III
3538	ASSISTENTE ADMIN	ASSISTENTE ADMINISTRATIVO I
3537	ASSISTENTE ADMIN	ASSISTENTE ADMINISTRATIVO
3536	ANALISTA RH IV	ANALISTA RH IV
3535	SUPERVISOR TRAFE	SUPERVISOR TRAFEGO I
3534	SUPERVISOR DE TR	SUPERVISOR DE TRAFEGO
3532	MOTORISTA INSTRU	MOTORISTA INSTRUTOR
3531	ENCARREGADO TRAF	ENCARREGADO TRAFEGO
3530	COORDENADOR DE T	COORDENADOR DE TRAFEGO III
3529	COORDENADOR DE T	COORDENADOR DE TRAFEGO II
3528	AUXILIAR TRAFEGO	AUXILIAR TRAFEGO A
3527	AUXILIAR DE TRAF	AUXILIAR DE TRAFEGO III
3526	AUXILIAR DE TRAF	AUXILIAR DE TRAFEGO II
3525	AUX MECANICO I	AUX MECANICO I
3523	COORD TRAFEGO	COORD TRAFEGO
3386	AUX DE TI I	AUX DE TI I
3378	AUX COMER	AUX COMER
3324	ANALIS COMPRAS I	ANALIS COMPRAS I
3290	MEC MONTADOR A	MEC MONTADOR A
3037	ANALISTA COMPRAS	ANALISTA COMPRAS II
2994	AUX FINANC IV	AUX FINANC IV
2993	ASS FATURAMEN IV	ASS FATURAMEN IV
2992	ANALIS TI III	ANALIS TI III
2991	MOT INSTRUTOR	MOT INSTRUTOR
2990	ENC OPERACIONAL	ENC OPERACIONAL
2989	MOT CARRETEIRO	MOT CARRETEIRO
2988	AUX EXPEDICAO	AUX EXPEDICAO
2987	ENC FILIAL	ENC FILIAL
2986	INSPETOR	INSPETOR
2985	ASS OPERACIONAL	ASSISTENTE OPERACIONAL
2984	AUX TI I	AUX TI I
2983	ANALI FINANC IV	ANALI FINANC IV
2982	SUP BORRACHARIA	SUP BORRACHARIA
2981	AUX MONIT I	AUX MONIT I
2980	TEC EDIFICACOES	TEC EDIFICACOES
2979	ASS TESOU V	ASS TESOU V
2978	SUP DE CONFERENC	SUP DE CONFERENC
2977	AUX DIGITALI III	AUX DIGITALI III
2976	MOT PARTICULAR	MOT PARTICULAR
2975	ANALI FINANC II	ANALI FINANC II
2974	ASS FINANC V	ASS FINANC V
2973	SUP DESEN SISTEM	SUP DESEN SISTEM
2972	AUX CONFEREN IV	AUX CONFEREN IV
2971	AUX FATURAME III	AUX FATURAME III
2970	ANA TESOURARIA I	ANA TESOURARIA I
2969	ASS PESSOAL I	ASS PESSOAL I
2968	ASS PESSOAL III	ASS PESSOAL III
2967	ASS FINANC I	ASS FINANC I
2966	ENC MANUT II	ENC MANUT II
2965	SUP TRAFEGO II	SUP TRAFEGO II
2964	COORD MONIT III	COORD MONIT III
2963	AUD MANUT II	AUD MANUT II
2962	ENC USINAGEM II	ENC USINAGEM II
2961	ENC ELETRICA II	ENC ELETRICA II
2960	CONTR MANUT IV	CONTR MANUT IV
2959	GER UNIDADE	GER UNIDADE
2958	TESOUREIRO	TESOUREIRO
2957	COORD TRAF III	COORD TRAF III
2956	ANALIS TI II	ANALIS TI II
2955	COORD TRAF IV	COORD TRAF IV
2954	ANALIS CUSTO I	ANALIS CUSTO I
2953	AUX TESOU III	AUX TESOU III
2952	COORD AUX VIAGEM	COORD AUX VIAGEM
2951	PINTOR PREDIAL	PINTOR PREDIAL
2950	ANALIS CUSTOS V	ANALIS CUSTOS V
2949	MOTOBOY	MOTOBOY
2948	JARDINEIRO	JARDINEIRO
2947	FISCAL PLATAFOR	FISCAL PLATAFOR
2946	MANOBRISTA	MANOBRISTA
2945	SERV GERAIS	SERV GERAIS
2944	AUX ADM	AUX ADM
2943	ELET II	ELET II
2942	AUX ADM I	AUX ADM I
2941	FRENTISTA	FRENTISTA
2940	MOTORISTA URB	MOTORISTA URB
2939	SERV EXTERNOS	SERV EXTERNOS
2938	PEDREIRO	PEDREIRO
2937	MECANICO III	MECANICO III
2936	FISCAL	FISCAL
2935	MECANICO I	MECANICO I
2934	MOTORISTA RODOV	MOTORISTA RODOV
2933	ENC TRAFEGO	ENC TRAFEGO
2922	TESTE 50%	TESTE 50%
501	ESTAGIARIO	ESTAGIARIO
4182	COORD CONTABILID	COORDENADOR CONTABILIDADE
3665	ZELADOR	ZELADOR
3657	ENC DE AGENCIA	ENC DE AGENCIA
3656	AUX ESTATISTICA	AUX ESTATISTICA V
3649	SUP BORRCAHARIA	SUP BORRCAHARIA
3524	ANA TESOURARIA I	ANA TESOURARIA I
3475	AUX ELETRICA	AUX ELETRICA
3474	AUX DE VIAGEM	AUX DE VIAGEM
3467	AUX ALMOX	AUX ALMOX
3456	SERV GERAIS	SERV GERAIS
3443	ASS PESSOAL I	ASS PESSOAL I
3395	ENC MANUT II	ENC MANUT II
3392	AUX JURIDICO I	AUX JURIDICO I
3391	ANALISTA RH V	ANALISTA RH V
3390	SOLDADOR V	SOLDADOR V
3389	CONF ENCOMENDAS	CONF ENCOMENDAS
3388	MANOBRISTA	MANOBRISTA
3385	DIRETOR	DIRETOR
3384	TORNEIRO M	TORNEIRO M
3383	TEC ELETR II	TEC ELETR II
3382	ARQUIVISTA	ARQUIVISTA
3381	BILHETEIRO	BILHETEIRO
3380	BILHETEIRO	BILHETEIRO
3379	ASS OPER I	ASS OPER I
3377	AUX COMPRAS	AUX COMPRAS
3376	MEC MONTA	MEC MONTA
3375	AUX TESOURARIA	AUX TESOURARIA
3374	ENC FAZENDA	ENC FAZENDA
3373	ASS VENDAS	ASS VENDAS
3372	MOT INSTRUTOR	MOT INSTRUTOR
3371	COORDENADOR	COORDENADOR
3370	AUX EXPED	AUX EXPED
3369	ENC FILIAL	ENC FILIAL
3368	ENC DE AGENCIA	ENC DE AGENCIA
3367	ENC FATURAMENTO	ENC FATURAMENTO
3366	ARRUMADOR	ARRUMADOR
3365	INSPETOR	INSPETOR
3364	ASS OPERACIONAL	ASS OPERACIONAL
3363	ANA PESSOAL I	ANA PESSOAL I
3362	AUX SINISTRO III	AUX SINISTRO III
3361	ASS COMPRAS I	ASS COMPRAS I
3360	ANALI CONTROL V	ANALI CONTROL V
3359	AUX BILHETAG V	AUX BILHETAG V
3358	TEC ENF TRAB II	TEC ENF TRAB II
3357	AUX SERV MED	AUX SERV MED
3016	ANALISTA JURIDIC	ANALISTA JURIDICO III
3015	ADVOGADO JUNIOR	ADVOGADO JUNIOR I
3014	AUXILIAR DE MOLE	AUXILIAR DE MOLEIRO
3013	MOLEIRO IV	MOLEIRO IV
3011	ASSISTENTE JURID	ASSISTENTE JURIDICO III
3010	SERVICOS GERAIS	SERVICOS GERAIS
3009	JARDINEIRO	JARDINEIRO
3008	ENCARREGADO GARA	ENCARREGADO GARAGEM I
3007	COORDENADOR DE M	COORDENADOR DE MANUTENCAO III
3006	AUXILIAR DE LANT	AUXILIAR DE LANTERNAGEM
3005	MANOBRISTA	MANOBRISTA
3004	AUXILIAR DE ALMO	AUXILIAR DE ALMOXARIFADO
3003	SUPERVISOR DE MA	SUPERVISOR DE MANUTENCAO
3002	GERENTE DE MANUT	GERENTE DE MANUTENCAO
3001	ENCARREGADO MANU	ENCARREGADO MANUTENCAO I
2999	DESPACHANTE	DESPACHANTE
2998	ASSISTENTE TI V	ASSISTENTE TI V
2997	COORDENADOR TI	COORDENADOR TI
2996	ANALISTA DE TI I	ANALISTA DE TI II
2995	ANALISTA BILHETA	ANALISTA BILHETAGEM I
3356	COORD MANUT I	COORD MANUT I
3355	AUD ALMOX II	AUD ALMOX II
3354	AUX JURIDICO I	AUX JURIDICO I
3353	ASS QUALIDADE V	ASS QUALIDADE V
3352	ASS EXPEDICAO	ASS EXPEDICAO
3351	ASS SINISTRO II	ASS SINISTRO II
3350	GER DA QUALIDADE	GER DA QUALIDADE
3349	ADVOGADO JR III	ADVOGADO JR III
3348	AUX JURIDICO III	AUX JURIDICO III
3347	AUX CONFERENCIA	AUX CONFERENCIA
3346	AUD FISCALIZACAO	AUD FISCALIZACAO
3345	ANALISTA ADM II	ANALISTA ADM II
3344	ANAL AMBIENT IV	ANAL AMBIENT IV
3343	ANALI TESOUR III	ANALI TESOUR III
3342	ANALIS ADM	ANALIS ADM
3341	ASS VENDAS II	ASS VENDAS II
3340	TEC SEG TRAB I	TEC SEG TRAB I
3339	TEC SEG TRAB IV	TEC SEG TRAB IV
3338	ASS QUALIDAD II	ASS QUALIDAD II
3337	ASS TESOU II	ASS TESOU II
3336	ASS DE SAC II	ASS DE SAC II
3335	AUX DE MONIT II	AUX DE MONIT II
3334	ASS FINANC IV	ASS FINANC IV
3333	ASS DOC V	ASS DOC V
3332	ASS DOC IV	ASS DOC IV
3331	ANALISTA DOC III	ANALISTA DOC III
3330	SUP ESTATISTICA	SUP ESTATISTICA
3329	ASS CONTABIL II	ASS CONTABIL II
3328	ASS FATURAM I	ASS FATURAM I
3327	AUX ESTATI V	AUX ESTATI V
3326	AUX ESTATI III	AUX ESTATI III
3325	AUX EXPEDI IV	AUX EXPEDI IV
3323	PORTEIRO A	PORTEIRO A
3322	PROMOT VENDA III	PROMOT VENDA III
3321	PROMOT VENDAS II	PROMOT VENDAS II
3320	PROMOT VENDAS I	PROMOT VENDAS I
3319	AUX FATURAME III	AUX FATURAME III
3318	AJUDANTE GERAL	AJUDANTE GERAL
3317	ENC MANOBRIST II	ENC MANOBRIST II
3316	ASSESSORA	ASSESSORA
3315	ASSESS IMPRENSA	ASSESS IMPRENSA
3314	ASS QUALIDAD III	ASS QUALIDAD III
3313	COORD PLANEJAMEN	COORD PLANEJAMEN
3312	GER JURID ADM	GER JURID ADM
3311	ADVOGADO PL III	ADVOGADO PL III
3310	ANALISTA JUR I	ANALISTA JUR I
3309	AUX SERV MED I	AUX SERV MED I
3308	ANALISTA RH V	ANALISTA RH V
3307	ASS PESSOAL IV	ASS PESSOAL IV
3306	ASS PESSOAL III	ASS PESSOAL III
3305	BILHETEIRO URBAN	BILHETEIRO URBAN
3304	AUX MONT RAD I	AUX MONT RAD I
3303	MECANICO IND IV	MECANICO INDUSTRIAL IV
3302	AUX TRAFEGO IV	AUX TRAFEGO IV
3301	SOLDADOR V	SOLDADOR V
3300	SUP CONTROLADORI	SUP CONTROLADORI
3299	ANALIS CONTAB II	ANALIS CONTAB II
3298	MOT RODOV I	MOT RODOV I
3297	MOT RODOV II	MOT RODOV II
3296	CAPOTEIRO A	CAPOTEIRO A
3295	COORD FISCALIZAC	COORD FISCALIZAC
3294	COORD BILHETA II	COORD BILHETA II
3293	ENC MANUT C	ENC MANUT C
3292	COORD MONIT I	COORD MONIT I
3291	ENC MANUT B	ENC MANUT B
3289	LANTERNEIRO A	LANTERNEIRO A
3288	ENC MANUT A	ENC MANUT A
3287	ENC ELETRICA B	ENC ELETRICA B
3286	AUX CONT MANUT	AUX CONT MANUT
3285	MEC INJECAO IV	MEC INJECAO IV
3284	MEC INJECAO II	MEC INJECAO II
3283	ENC SERV GER II	ENC SERV GER II
3282	ENC ALMOX II	ENC ALMOX II
3281	MONTADOR RAD I	MONTADOR RAD I
3280	MECANICO IND V	MECANICO IND V
3279	ENC INJECAO II	ENC INJECAO II
3278	PINTOR LETR IV	PINTOR LETR IV
3277	ENC LANTERN II	ENC LANTERN II
3276	CONF DE VEICULOS	CONF DE VEICULOS
3275	ADVOGADO JR II	ADVOGADO JR II
3274	ELETR TAC III	ELETR TAC III
3273	CONTR PNEUS I	CONTR PNEUS I
3272	AUX USINAGEM	AUX USINAGEM
3271	ENC CAPOTARIA I	ENC CAPOTARIA I
3270	ASS RH V	ASS RH V
3269	AUX TESOU I	AUX TESOU I
3268	MEC PNEUMAT V	MEC PNEUMAT V
3267	ASS RH	ASS RH
3266	TORNEIRO MEC IV	TORNEIRO MEC IV
3265	TRAB AGROPEC POL	TRAB AGROPEC POL
3264	TEC SEG TRAB V	TEC SEG TRAB V
3263	CAPOTEIRO III	CAPOTEIRO III
3262	ASS JURID II	ASS JURID II
3260	ASS RH II	ASS RH II
3259	CONTR PNEUS III	CONTR PNEUS III
3258	AUX TESOU III	AUX TESOU III
3257	EMISSOR DE FRETE	EMISSOR DE FRETE
3256	AUX MEC IND I	AUX MEC IND I
3255	AUX PESSOAL IV	AUX PESSOAL IV
3254	MECANICO IND I	MECANICO IND I
3253	PINTOR PREDIAL	PINTOR PREDIAL
3252	AUX PESSOAL III	AUX PESSOAL III
3251	ASS PESSOAL II	ASS PESSOAL II
3250	MOTORI MICRO	MOTORI MICRO
3249	BORRAC III	BORRAC III
3248	ANALISTA RH III	ANALISTA RH III
3247	ASS ADM II	ASS ADM II
3246	CONFER ENCOM	CONFER ENCOM
3245	TEC SEG TRAB II	TEC SEG TRAB II
3244	PEDREIRO B	PEDREIRO B
3243	AGENTE VENDAS	AGENTE VENDAS
3242	TORNEIRO MEC II	TORNEIRO MEC II
3241	ADV JUNIOR	ADV JUNIOR
3240	SOLDADOR I	SOLDADOR I
3239	ELETR PREDIAL	ELETR PREDIAL
3238	RECEPCIONISTA	RECEPCIONISTA
3237	AUX BORRACH I	AUX BORRACH I
3236	AUX ADM II	AUX ADM II
3235	PROMOTOR VENDAS	PROMOTOR VENDAS
3234	ALMOXARIFE	ALMOXARIFE
3233	COORD BILHETERIA	COORD BILHETERIA
3232	CAPOTEIRO II	CAPOTEIRO II
3231	AUX ADM	AUX ADM
3230	ENC MANOBRISTA I	ENC MANOBRISTA I
3229	SOLDADOR III	SOLDADOR III
3228	MOTORI COMPR	MOTORI COMPR
3227	MOTORI VEIC LEV	MOTORI VEIC LEV
3226	COBRADOR	COBRADOR
3225	MOTORISTA URB	MOTORISTA URB
3224	SERV EXTERNOS	SERV EXTERNOS
3223	CONTR MANUT I	CONTR MANUT I
3222	GERENTE DE RH	GERENTE DE RH
3221	AUX PESSOAL I	AUX PESSOAL I
3220	COBRADOR	COBRADOR URBANO INTERIOR
3219	AUXILIAR ADMINIS	AUXILIAR ADMINISTRATIVO III
3218	BILHETEIRO LIDER	BILHETEIRO LIDER
3217	ALMOXARIFE I	ALMOXARIFE I
3216	AUXILIAR DE CARG	AUXILIAR DE CARGAS
3215	AUXILIAR DE ALMO	AUXILIAR DE ALMOXARIFADO I
3214	MECANICO PNEUMAT	MECANICO PNEUMATICO II
3213	MECANICO PNEUMAT	MECANICO PNEUMATICO IV
3212	MECANICO PNEUMAT	MECANICO PNEUMATICO III
3017	ADVOGADO SENIOR	ADVOGADO SENIOR
3012	COORDENADOR JURI	COORDENADOR JURIDICO ADMINISTRATIVO
3211	MECANICO MONTADO	MECANICO MONTADOR III
3210	ENCARREGADO ELET	ENCARREGADO ELETRICA II
3209	ENCARREGADO DE E	ENCARREGADO DE ELETRICA A
3208	COMANDANTE DE AE	COMANDANTE DE AERONAVE
3207	CO PILOTO DE AER	CO PILOTO DE AERONAVES
3206	PINTOR V	PINTOR V
3205	PINTOR LETRISTA	PINTOR LETRISTA III
3204	AUDITOR DE MANUT	AUDITOR DE MANUTENCAO I
3203	SERVENTE PEDREIR	SERVENTE PEDREIRO A
3202	GERENTE DE LOGIS	GERENTE DE LOGISTICA
3201	AUXILIAR DE VIAG	AUXILIAR DE VIAGEM
3200	MOTORISTA RODOVI	MOTORISTA RODOVIARIO
3198	TEC ENFERMAGEM D	TEC ENFERMAGEM DO TRABALHO I ANALISTA
3197	MOLEIRO I	MOLEIRO I
3196	MOLEIRO III	MOLEIRO III
3195	FISCAL DE PLATAF	FISCAL DE PLATAFORMA
3194	TORNEIRO MECANIC	TORNEIRO MECANICO III
3193	MECANICO INDUSTR	MECANICO INDUSTRIAL III
3192	MECANICO INDUSTR	MECANICO INDUSTRIAL II
3191	AUXILIAR DE USIN	AUXILIAR DE USINAGEM I
3190	COORDENADOR DE T	COORDENADOR DE TRAFEGO IV
3189	MONTADOR RADIADO	MONTADOR RADIADOR III
3188	BORRACHEIRO I	BORRACHEIRO I
3187	ENCARREGADO DE B	ENCARREGADO DE BORRACHARIA I
3186	TECNICO ELETRONI	TECNICO ELETRONICA IV
3185	TECNICO ELETRONI	TECNICO ELETRONICA V
3184	BILHETEIRO	BILHETEIRO
3183	PINTOR III	PINTOR III
3182	SERVENTE DE PEDR	SERVENTE DE PEDREIRO
3181	TORNEIRO MECANIC	TORNEIRO MECANICO I
3180	MECANICO A	MECANICO A
3179	COBRADOR UBERLAN	COBRADOR UBERLANDIA
3177	ENCARREGADO TRAF	ENCARREGADO TRAFEGO
3176	AUXILIAR TRAFEGO	AUXILIAR TRAFEGO A
3175	TECNICO DE SEGUR	TECNICO DE SEGURANCA DO TRABALHO
3174	AUXILIAR ADMINIS	AUXILIAR ADMINISTRATIVO I
3173	ASSISTENTE ADMIN	ASSISTENTE ADMINISTRATIVO I
3172	AUXILIAR ADMINIS	AUXILIAR ADMINISTRATIVO V
3171	ASSISTENTE ADMIN	ASSISTENTE ADMINISTRATIVO
3170	SOLDADOR IV	SOLDADOR IV
3169	ASSISTENTE TESOU	ASSISTENTE TESOURARIA I
3168	ASSISTENTE TESOU	ASSISTENTE TESOURARIA IV
3167	MOTORISTA UBERLA	MOTORISTA UBERLANDIA
3166	ANALISTA RH IV	ANALISTA RH IV
3165	SUPERVISOR MANUT	SUPERVISOR MANUTENCAO I
3164	ASSISTENTE DE BI	ASSISTENTE DE BILHETAGEM III
3163	SUPERVISOR DE TR	SUPERVISOR DE TRAFEGO
3162	MECANICO MONTADO	MECANICO MONTADOR II
3161	AUXILIAR DE BILH	AUXILIAR DE BILHETAGEM I
3160	ENCARREGADO DE M	ENCARREGADO DE MANUTENCAO III
3159	COORDENADOR MANU	COORDENADOR MANUTENCAO III
3158	MOLEIRO V	MOLEIRO V
3157	MOLEIRO II	MOLEIRO II
3156	AUXILIAR DE MOLE	AUXILIAR DE MOLEIRO I
3155	MOLEIRO I	MOLEIRO I
3154	TESOUREIRO III	TESOUREIRO III
3153	TESOUREIRO II	TESOUREIRO II
3152	AUXILIAR TESOURA	AUXILIAR TESOURARIA IV
3151	ENCARREGADO DE E	ENCARREGADO DE ELETRICA A
3150	ELETRICISTA TACO	ELETRICISTA TACOGRAFISTA I
3149	ELETRICISTA III	ELETRICISTA III
3148	AUXILIAR DE ELET	AUXILIAR DE ELETRICA
3147	AUXILIAR DE LANT	AUXILIAR DE LANTERNAGEM I
3146	LANTERNEIRO V	LANTERNEIRO V
3145	AUXILIAR DE BORR	AUXILIAR DE BORRACHARIA
3144	BORRACHEIRO V	BORRACHEIRO V
3143	ENCARREGADO SERV	ENCARREGADO SERVICOS GERAIS I
3142	TEC SEGURANCA DO	TEC SEGURANCA DO TRABALHO III AUXILIA
3141	SUPERVISOR TRAFE	SUPERVISOR TRAFEGO II
3140	FISCAL URBANO	FISCAL URBANO
3139	MECANICO V	MECANICO V
3138	PEDREIRO A	PEDREIRO A
3137	AUXILIAR CONTROL	AUXILIAR CONTROLADOR DE MANUTENCAO I
3136	AUXILIAR DE PINT	AUXILIAR DE PINTURA I
3135	AUXILIAR DE CAPO	AUXILIAR DE CAPOTEIRO I
3134	CAPOTEIRO I	CAPOTEIRO I
3133	ALMOXARIFE III	ALMOXARIFE III
3132	ENCARREGADO DE A	ENCARREGADO DE ALMOXARIFADO I
3131	TESOUREIRO	TESOUREIRO
3130	AUXILIAR ADMINIS	AUXILIAR ADMINISTRATIVO IV
3128	COORDENADOR DE M	COORDENADOR DE MONITORAMENTO
3127	TEC SEGURANCA DO	TEC SEGURANCA DO TRABALHO II
3126	AGENTE DE ESTACA	AGENTE DE ESTACAO
3125	FISCAL	FISCAL
3124	PORTEIRO	PORTEIRO
3123	AUXILIAR DE CAPO	AUXILIAR DE CAPOTEIRO
3122	PINTOR II	PINTOR II
3121	PINTOR IV	PINTOR IV
3120	GERENTE DE UNIDA	GERENTE DE UNIDADE
3119	TECNICO EM SEGUR	TECNICO EM SEGURANCA DO TRABALHO
3118	ZELADOR	ZELADOR
3117	LANTERNEIRO I	LANTERNEIRO I
3116	AUXILIAR DE LANT	AUXILIAR DE LANTERNAGEM
3115	ENCARREGADO DE L	ENCARREGADO DE LANTERNAGEM I
3114	ALMOXARIFE IV	ALMOXARIFE IV
3113	ALMOXARIFE II	ALMOXARIFE II
3111	AUXILIAR DE ELET	AUXILIAR DE ELETRICA I
3110	ELETRICISTA V	ELETRICISTA V
3109	ASSISTENTE TESOU	ASSISTENTE TESOURARIA V
3108	TESOUREIRO I	TESOUREIRO I
3107	ENCARREGADO MANU	ENCARREGADO MANUTENCAO II
3106	COORDENADOR DE M	COORDENADOR DE MANUTENCAO II
3105	CONTROLADOR DE M	CONTROLADOR DE MANUTENCAO III
3104	CAPOTEIRO IV	CAPOTEIRO IV
3103	AUXILIAR DE PINT	AUXILIAR DE PINTURA
3102	PINTOR I	PINTOR I
3101	CONTROLADOR DE M	CONTROLADOR DE MANUTENCAO II
3100	CONTROLADOR DE M	CONTROLADOR DE MANUTENCAO IV
3099	PEDREIRO	PEDREIRO
3098	AUXILIAR DE TRAF	AUXILIAR DE TRAFEGO III
3097	COORDENADOR DE T	COORDENADOR DE TRAFEGO III
3096	COORDENADOR DE T	COORDENADOR DE TRAFEGO II
3095	SUPERVISOR TRAFE	SUPERVISOR TRAFEGO I
3094	COORDENADOR DE T	COORDENADOR DE TRAFEGO I
3093	AUXILIAR DE TRAF	AUXILIAR DE TRAFEGO I
3092	AUXILIAR DE TRAF	AUXILIAR DE TRAFEGO II
3091	SUPERVISOR DE TR	SUPERVISOR DE TRAFEGO III
3090	TEC SEGURANCA DO	TEC SEGURANCA DO TRABALHO II ANALISTA
3089	TEC SEGURANCA DO	TEC SEGURANCA DO TRABALHO V AUXILIAR
3087	TECNICO EM SEGUR	TECNICO EM SEGURANCA DO TRABALHO III
3086	AUXILIAR DE TRAF	AUXILIAR DE TRAFEGO
3085	BORRACHEIRO II	BORRACHEIRO II
3084	BORRACHEIRO IV	BORRACHEIRO IV
3083	LANTERNEIRO III	LANTERNEIRO III
3082	LANTERNEIRO IV	LANTERNEIRO IV
3081	ENCARREGADO DE L	ENCARREGADO DE LANTERNAGEM A
3080	LANTERNEIRO II	LANTERNEIRO II
3079	SECRETARIA	SECRETARIA
3078	MOTORISTA PARTIC	MOTORISTA PARTICULAR
3077	COZINHEIRA	COZINHEIRA
3076	ASSESSOR	ASSESSOR
3075	AUXILIAR CONTABI	AUXILIAR CONTABILIDADE II
3074	ASSISTENTE CONTA	ASSISTENTE CONTABIL IV
3073	ASSISTENTE CONTA	ASSISTENTE CONTABIL V
3072	AUXILIAR CONTABI	AUXILIAR CONTABIL IV
3071	ANALISTA CONTABI	ANALISTA CONTABIL III
3070	ANALISTA PESSOAL	ANALISTA PESSOAL II
3069	ASSISTENTE PESSO	ASSISTENTE PESSOAL V
3068	COORDENADOR DEPA	COORDENADOR DEPARTAMENTO PESSOAL II
3067	ASSISTENTE DE PE	ASSISTENTE DE PESSOAL I
3066	ADVOGADO SENIOR	ADVOGADO SENIOR III
3065	ASSISTENTE DE RH	ASSISTENTE DE RH I
3064	AUXILIAR DE RH I	AUXILIAR DE RH II
3063	COORDENADOR RH I	COORDENADOR RH II
3062	ASSISTENTE CONFE	ASSISTENTE CONFERENCIA III
3061	COORDENADOR MONI	COORDENADOR MONITORAMENTO III
3060	MOTOBOY	MOTOBOY
3059	AUXILIAR FINANCE	AUXILIAR FINANCEIRO
3058	AUXILIAR FINANCE	AUXILIAR FINANCEIRO V
3057	AUXILIAR FINANCE	AUXILIAR FINANCEIRO IV
3056	ANALISTA FINANCE	ANALISTA FINANCEIRO II
3055	GERENTE FINANCEI	GERENTE FINANCEIRO
3054	AUXILIAR FATURAM	AUXILIAR FATURAMENTO IV
3053	ANALISTA DE FATU	ANALISTA DE FATURAMENTO III
3052	LUBRIFICADOR	LUBRIFICADOR
3051	ANALISTA PROJETO	ANALISTA PROJETOS IV
3050	FRENTISTA	FRENTISTA
3049	MECANICO III	MECANICO III
3048	AUXILIAR MECANIC	AUXILIAR MECANICA I
3047	MECANICO II	MECANICO II
3046	AUXILIAR DE MECA	AUXILIAR DE MECANICA
3045	MECANICO IV	MECANICO IV
3044	MECANICO I	MECANICO I
3043	MOTORISTA CARRET	MOTORISTA CARRETEIRO
3042	MOTORISTA INSTRU	MOTORISTA INSTRUTOR
3041	AUXILIAR DE SERV	AUXILIAR DE SERVICOS MEDICOS II
3040	ANALISTA EXPEDIC	ANALISTA EXPEDICAO V
3038	COORDENADOR COMP	COORDENADOR COMPRAS
3036	ASSISTENTE DE CO	ASSISTENTE DE COMPRAS II
3035	ANALISTA DE CUST	ANALISTA DE CUSTOS V
3034	GERENTE DE CUSTO	GERENTE DE CUSTOS
3033	COORDENADOR DE C	COORDENADOR DE CUSTOS
3031	ENCARREGADO DE E	ENCARREGADO DE ELETRICA I
3030	ELETRICISTA IV	ELETRICISTA IV
3029	ELETRICISTA II	ELETRICISTA II
3028	ELETRICISTA I	ELETRICISTA I
3027	ELETRICISTA IV	ELETRICISTA IV
3026	ANALISTA SINISTR	ANALISTA SINISTRO I
3025	TESOUREIRO IV	TESOUREIRO IV
3024	AUXILIAR DE TESO	AUXILIAR DE TESOURARIA
3023	ENCARREGADO DE T	ENCARREGADO DE TESOURARIA
3022	ANALISTA TESOURA	ANALISTA TESOURARIA II
3021	ASSISTENTE TESOU	ASSISTENTE TESOURARIA III
3020	AUXILIAR JURIDIC	AUXILIAR JURIDICO IV
3019	AUXILIAR JURIDIC	AUXILIAR JURIDICO V
3018	ASSISTENTE JURID	ASSISTENTE JURIDICO I
4044	TORNEIRO MEC II	TORNEIRO MEC II
4043	TESOUREIRO I	TESOUREIRO I
4042	TEC SEG TRAB V	TEC SEG TRAB V
4041	TEC SEG TRAB I	TEC SEG TRAB I
4040	SUP ESTATISTICA	SUP ESTATISTICA
4039	SERVICOS GERAIS	SERVICOS GERAIS
4038	SERV EXTERNOS	SERV EXTERNOS
4037	PINTOR IV	PINTOR IV
4036	PEDREIRO B	PEDREIRO B
4035	MOTORISTA URB	MOTORISTA URB
4034	MOTORISTA URB	MOTORISTA URB
4033	MOTORISTA URB	MOTORISTA URB
4032	MOTORI VEIC LEV	MOTORI VEIC LEV
4031	MOTOBOY	MOTOBOY
4030	MOLEIRO IV	MOLEIRO IV
4029	MOLEIRO III	MOLEIRO III
4028	MOLEIRO II	MOLEIRO II
4027	MOLEIRO I	MOLEIRO I
4026	MECANICO V	MECANICO V
4025	MECANICO IV	MECANICO IV
4024	MECANICO III	MECANICO III
4023	MECANICO II	MECANICO II
4022	MECANICO I	MECANICO I
4021	MANOBRISTA	MANOBRISTA
4020	LANTERNEIRO IV	LANTERNEIRO IV
4019	LANTERNEIRO III	LANTERNEIRO III
4018	LANTERNEIRO II	LANTERNEIRO II
4017	LANTERNEIRO I	LANTERNEIRO I
4016	GER JURIDICO ADM	GER JURIDICO ADM
4015	FISCAL	FISCAL
4014	ENC GARAGEM I	ENC GARAGEM I
4013	ELET V	ELET V
4012	ELET IV	ELET IV
4011	ELET III	ELET III
4010	ELET II	ELET II
4009	COORDENADOR RH I	COORDENADOR RH I
4008	COBRADOR URB	COBRADOR URB
4007	COBRADOR URB	COBRADOR URB
4006	COBRADOR	COBRADOR
4005	BORRAC IV	BORRAC IV
4004	BORRAC II	BORRAC II
4003	AUX TRAFEGO II	AUX TRAFEGO II
4002	AUX TRAFEGO I	AUX TRAFEGO I
4001	AUX TESOU IV	AUX TESOU IV
4000	AUX TESOU III	AUX TESOU III
3999	AUX TESOU I	AUX TESOU I
3998	AUX MONITORAMENT	AUX MONITORAMENT
3997	AUX MECANICA I	AUX MECANICA I
3996	AUX MECANICA	AUX MECANICA
3995	AUX LANTERN I	AUX LANTERN I
3994	AUX LANTERN	AUX LANTERN
3993	AUX JURIDICO III	AUX JURIDICO III
3992	AUX FATURAM III	AUX FATURAM III
3991	AUX ESTATIST V	AUX ESTATIST V
3990	AUX ESTATIST III	AUX ESTATIST III
3989	AUX ELETRICA I	AUX ELETRICA I
3988	AUX ELETRICA	AUX ELETRICA
3987	AUX DIGITALI III	AUX DIGITALI III
3986	AUX CONTABIL IV	AUX CONTABIL IV
3985	AUX CONTABIL II	AUX CONTABIL II
3984	AUX BILHETAG V	AUX BILHETAG V
3983	ASS TESOUR III	ASSISTENTE TESOURARIA III
3982	ASS QUALIDAD V	ASSISTENTE QUALIDADE V
3981	ASS QUALIDAD III	ASSISTENTE QUALIDADE III
3980	ASS JURIDICO I	ASSISTENTE JURIDICO I
3979	ASS JURIDICO II	ASSISTENTE JURIDICO II
3978	ASS FATURAM I	ASSISTENTE FATURAMENTO I
3977	ASS CONTABIL IV	ASSISTENTE CONTABIL IV
3976	ASS CONTABIL II	ASSISTENTE CONTABIL II
3975	ANA CUSTOS V	ANALISTA CUSTOS V
3974	ANA CONTABIL II	ANALISTA CONTABIL II
3972	ANA AMBIENT IV	ANA AMBIENT IV
3971	AGENTE ESTACAO	AGENTE ESTACAO
3965	ASS QUALIDADE V	ASSISTENTE QUALIDADE V
3964	ASS QUALIDAD III	ASSISTENTE QUALIDADE III
3962	AUX TEC SEG DO T	AUX TEC SEG DO TRABALHO III
3961	AUX ADM IV	AUX ADM IV
3960	JARDINEIRO	JARDINEIRO
3959	ENC MAN II	ENC MAN II
3958	ENC MAN II	ENC MAN II
3957	COORD MONITORAME	COORD MONITORAMENTO
3956	AUX MECANICA	AUX MECANICA
3955	SUP TRAF II	SUP TRAF II
3954	FISCAL URBANO	FISCAL URBANO
3953	AGENTE DE ESTACA	AGENTE DE ESTACAO
3952	TESOUREIRO	TESOUREIRO
3951	TESOUREIRO III	TESOUREIRO III
3950	TESOUREIRO II	TESOUREIRO II
3949	TEC SEG TRABALHO	TEC SEG TRABALHO III AUXILIAR
3948	AUX TESOURARIA I	AUX TESOURARIA IV
3947	AUX BILHETAGEM I	AUX BILHETAGEM I
3946	ASSIST TESOURARI	ASSIST TESOURARIA V
3945	ASSIST PESSOAL I	ASSIST PESSOAL I
3944	SUP TRAFEGO	SUP TRAFEGO
3943	SUP TRAFEGO III	SUP TRAFEGO III
3942	COORD TRAFEGO I	COORD TRAFEGO I
3941	MOT PARTICULAR	MOT PARTICULAR
3940	MOT CARRETEIRO	MOT CARRETEIRO
3939	COORD MON III	COORD MON III
3937	ENC GARAGEM I	ENC GARAGEM I
3936	COORD TRAF I	COORD TRAF I
3935	AUX TRAFEGO I	AUX TRAFEGO I
3934	ZELADOR	ZELADOR
3933	FRENTISTA	FRENTISTA
3932	AUX MECANICO I	AUX MECANICO I
3931	ALMOXARIFE IV	ALMOXARIFE IV
3929	GERENTE FINANCEI	GERENTE FINANCEIRO
3928	GERENTE DE CUSTO	GERENTE DE CUSTOS
3927	ENC TESOURARIA	ENC TESOURARIA
3926	DESPACHANTE	DESPACHANTE
3925	COZINHEIRA	COZINHEIRA
3923	TESOUREIRO IV	TESOUREIRO IV
3922	TEC SEG TRAB III	TEC SEG TRAB III
3921	TEC SEG TRAB II	TEC SEG TRAB II ANALISTA
3920	TEC SEG TRAB V A	TEC SEG TRAB V AUXILIAR
3919	SECRETARIA	SECRETARIA
3918	MOTOBOY	MOTOBOY
3917	TORN MECANICO I	TORN MECANICO I
3916	TEC SEG TRABALHO	TEC SEG TRABALHO III
3915	TEC SEG TRABALHO	TEC SEG TRABALHO
3914	SUP TRAFEGO I	SUP TRAFEGO I
3913	SUP MAN I	SUP MAN I
3912	SUP TRAFEGO	SUP TRAFEGO
3911	SERV PEDREIRO	SERV PEDREIRO
3910	PINTOR III	PINTOR III
3909	PINTOR II	PINTOR II
3908	MOLEIRO IV	MOLEIRO IV
3907	MEDICO EXAMINADO	MEDICO EXAMINADOR
3906	MECANICO A	MECANICO A
3905	ENC TRAFEGO	ENC TRAFEGO
3904	ENC SERV GERAIS	ENC SERV GERAIS I
3903	ENC LANTERNAGEM	ENC LANTERNAGEM I
3902	ENC ELETRICA I	ENC ELETRICA I
3901	ELETRICISTA V	ELETRICISTA V
3900	ELETRICISTA II	ELETRICISTA II
3899	COORD TRAF III	COORD TRAF III
3898	COORD TRAF II	COORD TRAF II
3897	CONT MANUT III	CONT MANUT III
3896	BORRACHEIRO II	BORRACHEIRO II
3895	AUX TRAFEGO A	AUX TRAFEGO A
3894	AUX TRAFEGO III	AUX TRAFEGO III
3893	AUX TRAFEGO II	AUX TRAFEGO II
3892	AUX TRAFEGO	AUX TRAFEGO
3891	AUX PINTURA I	AUX PINTURA I
3890	AUX LANTERNAGEM	AUX LANTERNAGEM
3889	AUX ELETRICA	AUX ELETRICA
3888	AUX ELETRICA I	AUX ELETRICA I
3887	AUX CAPOTEIRO	AUX CAPOTEIRO
3886	AUX ADM I	AUX ADM I
3885	ASSIST TI V	ASSIST TI V
3884	ASSIST TESOURARI	ASSIST TESOURARIA I
3883	ASSIST TESOURARI	ASSIST TESOURARIA IV
3882	ASSIST BILHETAGE	ASSIST BILHETAGEM III
3881	ASSIST ADM I	ASSIST ADM I
3880	ASSIST ADM	ASSIST ADM
3879	ANAL RH IV	ANAL RH IV
3877	BILHETEIRO LIDER	BILHETEIRO LIDER
3876	MOT RODOVIARIO	MOT RODOVIARIO
3874	FISCAL	FISCAL
3873	FISCAL DE PLATAF	FISCAL DE PLATAFORMA
3872	COORD TRAFEGO IV	COORD TRAFEGO IV
3871	AUX VIAGEM	AUX VIAGEM
3870	AUX ALMOX I	AUX ALMOX I
3869	TORNEIRO MECANIC	TORNEIRO MECANICO III
3868	TEC ELETRONICA I	TEC ELETRONICA IV
3867	TEC ELETRONICA V	TEC ELETRONICA V
3866	SOLDADOR IV	SOLDADOR IV
3865	PINTOR LETRISTA	PINTOR LETRISTA III
3864	MONTADOR RADIADO	MONTADOR RADIADOR III
3863	MOLEIRO III	MOLEIRO III
3862	MECANICO PNEUMAT	MECANICO PNEUMATICO II
3861	MECANICO PNEUMAT	MECANICO PNEUMATICO IV
3860	MECANICO PNEUMAT	MECANICO PNEUMATICO III
3859	MECANICO MONTADO	MECANICO MONTADOR III
3858	MECANICO MONTADO	MECANICO MONTADOR II
3857	MECANICO INDUSTR	MECANICO INDUSTRIAL III
3856	MECANICO INDUSTR	MECANICO INDUSTRIAL II
3855	ENC MANUTENCAO I	ENC MANUTENCAO II
3854	ENC ELETRICA II	ENC ELETRICA II
3853	ENCARREGADO BORR	ENCARREGADO BORRACHARIA I
3852	BORRACHEIRO I	BORRACHEIRO I
3851	AUX DE CARGAS	AUX DE CARGAS
3850	AUX ALMOXARIFADO	AUX ALMOXARIFADO I
3849	AUDITOR MANUT I	AUDITOR MANUT I
3848	ALMOXARIFE II	ALMOXARIFE II
3847	ALMOXARIFE I	ALMOXARIFE I
3846	AUX ADM III	AUX ADM III
3845	TEC ENFERMAGEM D	TEC ENFERMAGEM DO TRABALHO I ANALISTA
3844	MEDICO DO TRABAL	MEDICO DO TRABALHO
3843	GERENTE DE LOGIS	GERENTE DE LOGISTICA
3842	DIRETOR	DIRETOR
3841	COORD TI	COORD TI
3840	COORD RH II	COORD RH II
3839	COORD DEPTO PESS	COORD DEPTO PESSOAL II
3838	COORD CUSTOS	COORD CUSTOS
3837	COORD COMPRAS	COORD COMPRAS
3836	COORD JUR ADMINI	COORD JUR ADMINISTRATIVO
3835	AUX JURIDICO V	AUX JURIDICO V
3834	AUX FINANCEIRO	AUX FINANCEIRO
3833	AUX FINANCEIRO V	AUX FINANCEIRO V
3832	AUX FATURAMENTO	AUX FATURAMENTO IV
3831	AUX SERVICOS MED	AUX SERVICOS MEDICOS II
3830	AUX RH II	AUX RH II
3829	AUX CONTABIL II	AUX CONTABIL II
3828	AUX FINANCEIRO V	AUX FINANCEIRO V
3827	AUX FINANCEIRO I	AUX FINANCEIRO IV
3826	ASSIST TI V	ASSIST TI V
3825	ASSIST PESSOAL V	ASSIST PESSOAL V
3824	ASSIST JURIDICO	ASSIST JURIDICO III
3823	ASSIST RH I	ASSIST RH I
3822	ASSIST CONTABIL	ASSIST CONTABIL V
3821	ASSIST CONF III	ASSIST CONF III
3820	ASSIST COMPRAS I	ASSIST COMPRAS II
3819	ASSIST BILHETAGE	ASSIST BILHETAGEM I
3818	ASSIST CONTABIL	ASSIST CONTABIL IV
3817	ASSESSOR	ASSESSOR
3816	ASSIST TESOURARI	ASSIST TESOURARIA III
3815	ASSIST PESSOAL I	ASSIST PESSOAL I
3814	ANAL TESOURARIA	ANAL TESOURARIA II
3813	ANAL SINISTRO I	ANAL SINISTRO I
3812	ANAL PESSOAL II	ANAL PESSOAL II
3811	ANAL JURIDICO II	ANAL JURIDICO III
3810	ANAL EXPEDICAO V	ANAL EXPEDICAO V
3809	ANAL FATURAMENTO	ANAL FATURAMENTO III
3808	ANAL CONTABIL II	ANAL CONTABIL III
3807	ANAL COMPRAS II	ANAL COMPRAS II
3806	ANAL TI II	ANAL TI II
3805	ANAL CUSTOS V	ANAL CUSTOS V
3804	ANAL FINANC II	ANAL FINANC II
3803	ANAL PROJETO IV	ANAL PROJETO IV
3802	ADV SENIOR III	ADV SENIOR III
3801	ADV JUNIOR	ADV JUNIOR
3800	TESOUREIRO I	TESOUREIRO I
3799	TEC SEG TRABALHO	TEC SEG TRABALHO
3797	GERENTE DE UNIDA	GERENTE DE UNIDADE
3796	ENG SEG DO TRABA	ENG SEG DO TRABALHO
3795	AUX JURIDICO IV	AUX JURIDICO IV
3794	AUX TESOURARIA	AUX TESOURARIA
3793	ASSIST TESOURARI	ASSIST TESOURARIA V
3792	SUP MANUTENCAO	SUP MANUTENCAO
3791	GER MANUTENCAO	GER MANUTENCAO
3790	CONTR MANUTENCAO	CONTR MANUTENCAO IV
3788	EMISSOR DE FRETE	EMISSOR DE FRETE
3786	PINTOR I	PINTOR I
3785	MOLEIRO V	MOLEIRO V
3784	MOLEIRO I	MOLEIRO I
3783	MECANICO V	MECANICO V
3782	LANTERNEIRO IV	LANTERNEIRO IV
3781	FRENTISTA	FRENTISTA
3780	ENC ELETRICA A	ENC ELETRICA A
3779	ENC MANUTENCAO	ENC MANUTENCAO III
3778	ENC LANTERNAGEM	ENC LANTERNAGEM I
3777	ENC ALMOXARIFADO	ENC ALMOXARIFADO I
3776	ELETRICISTA I	ELETRICISTA I
3775	CONT MANUTENCAO	CONT MANUTENCAO II
3774	CAPOTEIRO I	CAPOTEIRO I
3773	BORRACHEIRO II	BORRACHEIRO II
3772	AUX PINTURA I	AUX PINTURA I
3771	AUX LANTERNAGEM	AUX LANTERNAGEM I
3770	ALMOXARIFE III	ALMOXARIFE III
3769	SERVIÇOS GERAIS	SERVIÇOS GERAIS
3768	PINTOR IV	PINTOR IV
3767	PINTOR II	PINTOR II
3766	PEDREIRO A	PEDREIRO A
3765	MOLEIRO II	MOLEIRO II
3764	MECANICO IV	MECANICO IV
3763	MECANICO III	MECANICO III
3762	MECANICO II	MECANICO II
3761	MECANICO I	MECANICO I
3760	MANOBRISTA	MANOBRISTA
3759	LUBRIFICADOR	LUBRIFICADOR
3758	LANTERNEIRO V	LANTERNEIRO V
3757	LANTERNEIRO II	LANTERNEIRO II
3756	LANTERNEIRO I	LANTERNEIRO I
3755	ENC MANUTENCAO I	ENC MANUTENCAO I
3754	ENC LANTERNAGEM	ENC LANTERNAGEM I
3753	ENC ELETRICA I	ENC ELETRICA I
3752	ENC ALMOXARIFADO	ENC ALMOXARIFADO I
3751	ELET TACOGRAFIST	ELET TACOGRAFISTA I
3750	ELETRICISTA IV	ELETRICISTA IV
3749	ELETRICISTA III	ELETRICISTA III
3748	.ELETRICISTA II	ELETRICISTA II
3747	COORD MAN III	COORD MAN III
3746	COORD MAN II	COORD MAN II
3745	BORRACHEIRO V	BORRACHEIRO V
3744	BORRACHEIRO IV	BORRACHEIRO IV
3743	AUX PINTURA	AUX PINTURA
3742	AUX MOLEIRO I	AUX MOLEIRO I
3741	AUX MOLEIRO	AUX MOLEIRO
3740	AUX MECANICA I	AUX MECANICA I
3739	AUX MECANICA	AUX MECANICA
3738	AUX LANTERNAGEM	AUX LANTERNAGEM I
3737	AUX LANTERNAGEM	AUX LANTERNAGEM
3736	AUX ELETRICA	AUX ELETRICA
3735	AUX ELETRICA I	AUX ELETRICA I
3734	AUX CAPOTEIRO I	AUX CAPOTEIRO I
3733	AUX BORRACHARIA	AUX BORRACHARIA
3732	AUX ALMOXARIFADO	AUX ALMOXARIFADO
3731	AUX CONTROLADOR	AUX CONTROLADOR MAN I
3724	AUX ELETRICA	AUX ELETRICA
3722	MECANICO IV	MECANICO IV
3721	AUX DE SAC I	AUX DE SAC I
3705	PINTOR V	PINTOR V
3704	ENC INJECAO II	ENC INJECAO II
3663	TEC SEG TRAB V	TEC SEG TRAB V
3662	ASS ADM	ASS ADM
3661	INSPETOR	INSPETOR
3659	ASS OPERACIONAL	ASS OPERACIONAL
3658	ASS OPERACIONAL	ASS OPERACIONAL
3651	ASSISTENTE CONT	ASSISTENTE CONT
3650	AUXILIAR CONTABI	AUXILIAR CONTABI
3645	MONTADOR RAD I	MONTADOR RAD I
3521	ENC LANTERN II	ENC LANTERN II
3520	ENC FILIAL	ENC FILIAL
3511	ELET IV	ELET IV
3505	CONFER ENCOM	CONFER ENCOM
3495	BILHETEIRO	BILHETEIRO
3492	AUXILIAR DE VIAG	AUXILIAR DE VIAG
3484	AUXILIAR DE CARG	AUXILIAR DE CARG
3476	AUX EXPED	AUX EXPED
3472	MOT CARRETEIRO	MOT CARRETEIRO
3471	AUX CONFERENCIA	AUX CONFERENCIA
3465	AUX ADM I	AUX ADM I
3463	TEC EDIFICACOES	TEC EDIFICACOES
3462	AUX ADM	AUX ADM
3451	PINTOR PREDIAL	PINTOR PREDIAL
3450	ASSISTENTE RH	ASSISTENTE RH
3444	PEDREIRO	PEDREIRO
3442	ASS OPERACIONAL	ASS OPERACIONAL
3440	MOTORISTA RODOVI	MOTORISTA RODOVI
3439	ASS JURIDICO II	ASS JURIDICO II
3437	ASS EXPEDICAO	ASS EXPEDICAO
3434	ARRUMADOR	ARRUMADOR
3433	ARQUIVISTA	ARQUIVISTA
3432	MOT PARTICULAR	MOT PARTICULAR
3428	ANALISTA JUR I	ANALISTA JUR I
3427	MECANICO I	MECANICO I
3424	ANALISTA TI III	ANALISTA TI III
3423	ANALISTA TI II	ANALISTA TI II
3416	LANTERNEIRO IV	LANTERNEIRO IV
3412	LANTERNEIRO III	LANTERNEIRO III
3411	ALMOXARIFE	ALMOXARIFE
3394	ENC MANUT B	ENC MANUT B
2932	ENC OPERACIONAL	ENC OPERACIONAL
2931	ENC COBRANCA	ENC COBRANCA
2930	ANALIS CUSTOS	ANALIS CUSTOS
2929	ANALISTA CONT I	ANALISTA CONT I
2928	ASS CONTABIL II	ASS CONTABIL II
2927	ASS CONTABIL IV	ASS CONTABIL IV
2926	PORTEIRO A	PORTEIRO A
2925	AUX FATURAME III	AUX FATURAME III
2924	ANALIS CONTAB II	ANALIS CONTAB II
2923	PORTEIRO	PORTEIRO
4486	AUX. ADMINISTRAT	AUXILIAR ADMINISTRATIVO
4482	AUX.POLIDOR I	AUX.POLIDOR I
4480	AUX. POLIDOR I	AUXILIAR POLIDOR I
4460	GER ADMINISTRATI	GERENTE ADMINISTRATIVO
4447	TEC SEG TRAB I	TEC SEG TRAB I
4446	TEC SEG TRAB V	TEC SEG TRAB V
4445	TEC SEG TRAB II	TEC SEG TRAB II
4435	AUX RH	AUXILIAR DE  RH
4430	ENC MECANICA I	ENC MECANICA I
4429	TEC.ELETRONICA I	TECNICO ELETRONICA I
4426	ENC.CONTROLE II	ENCARREGADO DE CONTROLE II
4423	ANL PESSOAL V	ANALISTA DE PESSOAL V
4416	AUX FISCAL V	AUX FISCAL V
4412	PINTOR LET V	PINTOR LETRISTA  V
4411	MEC IND V	MECANICO INDUSTRIAL V
4410	MEC IND III	MECANICO  INDUSTRIAL III
4408	ANL JURIDICO IV	ANALISTA JURIDICO IV
4407	ASSIST. TEC SEG	ASSISTENTE TECNICO SEGURANCA TRABALHO III
4405	AUX DE TI II	AUX DE TI II
4403	AUX FISCAL IV	AUXILIAR FISCAL IV
4402	ENC SERVICOS GER	ENCARREGADO SERVICOS GERAIS
4401	ENC MECANICA II	ENCARREGADO MECANICA II
4400	AUX SBE III	AUXILIAR SBE III
4399	LANTERNEIRO IV	LANTERNEIRO IV
4398	ELET PREDIAL V	ELETRICISTA PREDIAL V
4397	ENC CONTROLE I	ENCARREGADO DE CONTROLE I
4395	ASSIST FINANCEIR	ASSIST FINANCEIRO
4390	ASSIST FISCAL IV	ASSIST FISCAL IV
4371	ANL FISCAL II	ANALISTA FISCAL II
4361	COOR BILHETE IV	COORDENADOR DE BILHETERIA IV
4360	COOR BILHETE III	COORDENADOR DE BILHETERIA III
4355	AUX SINISTRO V	AUXILIAR DE SINISTRO V
4352	AUX SAC V	AUXILIAR DE SAC V
4349	AUX SAC II	AUXILIAR DE SAC II
4331	AUX DE CUSTOS IV	AUXILIAR DE CUSTOS IV
4330	AUX CONF II	AUXILIAR DE CONFERENCIA II
4320	AUDITOR ALMOX	AUDITOR DE ALMOXARIFADO
4318	ASS JURIDICO I	ASSISTENTE JURIDICO I
4314	ASS TESOURAR V	ASSISTENTE DE TESOURARIA V
4313	ASS TESOURAR IV	ASSISTENTE DE TESOURARIA IV
4312	ASS TESOURAR III	ASSISTENTE DE TESOURARIA III
4311	ASS TESOURAR II	ASSISTENTE DE TESOURARIA II
4310	ASS TESOURAR I	ASSISTENTE DE TESOURARIA I
4289	ASS FROTA III	ASSISTENTE DE FROTA III
4280	ASS CONFERENC I	ASSISTENTE DE CONFERENCIA I
4279	ASS CONFERENC IV	ASSISTENTE DE CONFERENCIA IV
4203	ANL AMBIENT V	ANALISTA AMBIENTAL V
4199	PILOTO DE AERONA	PILOTO DE AERONAVES
4196	COORD TST III	TECNICO SEGURANÇA DO TRABALHO III COORDENADOR
4111	GESTOR ADM	GESTOR ADMINISTRATIVO
4088	TEC SEG TRAB IV	TEC SEG TRAB IV
3924	ASSIST BILHETAGE	ASSIST BILHETAGEM I
3703	ANALISTA DE RH	ANALISTA DE RH
2921	CADASTRAR	CADASTRAR
2920	CADASTRAR	CADASTRAR
2919	CADASTRAR	CADASTRAR
2918	CADASTRAR	CADASTRAR
2917	CADASTRAR	CADASTRAR
2916	CADASTRAR	CADASTRAR
2915	CADASTRAR	CADASTRAR
2914	CADASTRAR	CADASTRAR
2913	CADASTRAR	CADASTRAR
2912	CADASTRAR	CADASTRAR
2911	CADASTRAR	CADASTRAR
2910	CADASTRAR	CADASTRAR
2909	SUP MANUTENCAO	SUPERVISOR DE MANUTENCAO
2907	ANAL CONT III	ANALISTA CONTABIL III
2441	ARQUIVISTA	ARQUIVISTA
2437	BILHET LIDER	BILHETEIRO LIDER
2436	BILHETEIRO IV	BILHETEIRO IV
2419	ASS OPERAC I	ASSISTENTE DE OPERAÇÕES I
2373	GER CONTABILIDAD	GERENTE CONTABILIDADE
2367	FISCAL III	FISCAL III
2366	FISCAL II	FISCAL II
2365	FISCAL I	FISCAL I
2088	COORD CONTABILID	COORDENADOR (A) DE CONTABILIDADE
2058	ENC FAZENDA	ENCARREGADO DE FAZENDA
2052	ASS COMERCIAL	ASSISTENTE COMERCIAL
2050	ASS VENDAS	ASSISTENTE DE VENDAS
2036	ENC TI I	ENCARREGADO TI I
2035	ASS BILHETERIA	ASSISTENTE BILHETERIA
2028	GER LOGISTICA	GERENTE DE LOGISTICA
2022	AUX  EXPEDICAO	AUXILIAR DE EXPEDICAO
2018	ENC DE AGENCIA	ENCARREGADO DE AGENCIA
2017	ENC COBRANCA	ENCARREGADO DE COBRANCA
2016	ENC FATURAMENTO	ENCARREGADO DE FATURAMENTO
2014	CASEIRO	CASEIRO
2011	COMPRADOR	COMPRADOR
2010	ARRUMADOR	ARRUMADOR
2009	AUX CUSTOS	AUXILIAR DE CUSTOS
2008	INSPETOR	INSPETOR
2006	ASS OPERACIONAL	ASSISTENTE OPERACIONAL
2003	CHAPA DE FRENTE	CHAPA DE FRENTE
1072	COORD MAN III	COORDENADOR DE MANUTENÇÃO III
1071	ANALIS CUSTOS	ANALISTA DE CUSTOS
1050	AJUD COLETA ENTR	AJUDANTE DE COLETA E ENTREGA
1049	TECNICO INFORMAT	TECNICO INFORMATICA
1048	FARMACEUTICO	FARMACEUTICO
1042	ASS EXPEDICAO	ASSISTENTE DE EXPEDICAO
1036	CONSUL DE VENDAS	CONSULTOR DE VENDAS
1027	AGENTE DE SOLO	AGENTE DE SOLO
1020	ANALI CRIACAO II	ANALISTA DE CRIACAO II
1016	ANALIS TESOU V	ANALISTA TESOURARIA V
989	SUPERV FAZENDA	SUPERVISOR DE FAZENDA
981	ANALI ESTAT I	ANALISTA ESTATISTICA I
980	ASS DOC V	ASSISTENTE DOCUMENTOS V
976	AUX DIGITALI III	AUXILIAR DIGITALIZACAO III
939	ANALI EXPED V	ANALISTA EXPEDICAO V
938	AUX ESTATI V	AUXILIAR ESTATISTICA V
936	AUX EXPEDI IV	AUXILIAR EXPEDICAO IV
935	AUX ESTATI II	AUXILIAR ESTATISTICA II
927	ANALI COMPRAS V	ANALISTA COMPRAS V
925	ANALI COMPRAS IV	ANALISTA COMPRAS IV
918	ENC ELETRICA  A	ENCARREGADO DE ELETRICA  A
913	AUX TRAFEGO A	AUXILIAR TRAFEGO A
911	PROMOT VENDA III	PROMOTOR VENDAS III
910	PROMOT VENDAS II	PROMOTOR VENDAS II
909	PROMOT VENDAS I	PROMOTOR DE VENDAS I
906	AUX ADM A	AUXILIAR ADMINISTRATIVO A
903	ANALIS QUAL  III	ANALISTA QUALIDADE III
896	SUPERI PLANEJAME	SUPERINTENDENTE PLANEJAMENTO
893	SUPERI SUPRIMENT	SUPERINTENDENTE SUPRIMENTOS
892	SUPERI COMERCIAL	SUPERINTENDENTE COMERCIAL
891	ASS QUALIDAD III	ASSISTENTE QUALIDADE III
884	COORD JUR ADM	COORDENADOR JURIDICO ADMINISTRATIVO
879	GER JURID CIVEL	GERENTE JURIDICO CIVEL
875	GER JURID TRAB	GERENTE JURIDICO TRABALHISTA
858	ASSISTENTE RH IV	ASSISTENTE RH IV
832	VIDRACEIRO	VIDRACEIRO
821	ANALIST CONT III	ANALISTA CONTABIL III
715	COORD QUALIDADE	COORDENADOR DE QUALIDADE
702	ENC ALMOXARIF A	ENCARREGADO ALMOXARIFE A
688	PINTOR LETR A	PINTOR LETRISTA A
687	PEDREIRO A	PEDREIRO A
681	ENC MANUT A	ENCARREGADO MANUTENCAO A
679	ENC LANTERN A	ENCARREGADO LANTERNAGEM A
676	ENC ELETRICA B	ENCARREGADO DE ELETRICA B
675	ENC ELETRICA A	ENCARREGADO DE ELETRICA A
589	ENC. ARRECADACAO	ENCARREGADO DE ARRECADACAO
557	GER LOGISTICA	GERENTE DE LOGISTICA
536	COORD MONIT	COORDENADOR DE MONITORAMENTO
495	DOMADOR	DOMADOR
457	TESOUREIRO III	TESOUREIRO III
416	POLIDOR	POLIDOR
412	COORD SEG TRAB	COORDENADOR DE SEGURANCA DO TRABALHO
410	CAPOTEIRO I	CAPOTEIRO I
380	COMPRADOR III	COMPRADOR III
335	AUX BILHETAG	AUXILIAR DE BILHETAGEM
334	TEC SEG TRAB IV	TECNICO SEGURANCA DO TRABALHO IV
328	AUD ALMOX	AUDITOR DE ALMOXARIFADO
321	CO PILOTO DE AER	CO PILOTO DE AERONAVES
304	TESOUREIRO IV	TESOUREIRO IV
303	TESOUREIRO	TESOUREIRO
299	TEC SEG TRAB III	TECNICO EM SEGURANCA DO TRABALHO III
285	ADV PLENO	ADVOGADO PLENO
284	ADVOGADO SR	ADVOGADO SENIOR
270	COMAND AERONAVE	COMANDANTE DE AERONAVE
204	ENC TESOURARIA	ENCARREGADO DE TESOURARIA
147	PROMOTOR VENDAS	PROMOTOR DE VENDAS
128	SUP VENDAS	SUPERVISOR DE VENDAS
112	TESOUREIRO I	TESOUREIRO I
106	ASS ADM	ASSISTENTE ADMINISTRATIVO
90	TEC SEG TRAB	TECNICO DE SEGURANCA DO TRABALHO
89	TESOUREIRO II	TESOUREIRO II
66	AUX ADM I	AUXILIAR ADMINISTRATIVO I
63	LUBRIFICADOR I	LUBRIFICADOR I
4396	MOTORISTA HORIST	MOTORISTA HORISTA UBERLANDIA
4387	JOVEM APRENDIZ M	JOVEM APRENDIZ MECANICO DE VEICULOS
4385	JOVEM APRENDIZ L	JOVEM APRENDIZ LOGISTICA
4382	JOVEM APRENDIZ	JOVEM APRENDIZ
4378	ESTAGIARIO	ESTAGIARIO
4156	COBRADOR URBANO	COBRADOR URBANO
4140	MEDICO TRABALHO	MEDICO TRABALHO
4096	MECANICO II	MECANICO II
4095	AUX MECANICA I	AUX MECANICA I
3969	COORDENAR RH I	COORDENAR RH I
3938	COBRADOR	COBRADOR
3875	MOT INSTRUTOR	MOT INSTRUTOR
3798	JOVEM APRENDIZ	JOVEM APRENDIZ
3729	MOTORISTA UBERLA	MOTORISTA UBERLANDIA
3728	MOTORISTA INSTRU	MOTORISTA INSTRUTOR
3723	MOTORISTA URB	MOTORISTA URB
3699	MOTORISTA URBANO	MOTORISTA URBANO SETRA
3667	COBRADOR	COBRADOR
3548	MEDICO EXAMINADO	MEDICO EXAMINADOR
3547	JOVEM APRENDIZ	JOVEM APRENDIZ
3533	MOTORISTA UBERLA	MOTORISTA UBERLANDIA
3387	ESTAGIARIO	ESTAGIARIO
3199	MEDICO DO TRABAL	MEDICO DO TRABALHO
3178	MEDICO EXAMINADO	MEDICO EXAMINADOR
3129	COBRADOR URBANO	COBRADOR URBANO SINTRAM
3112	MOTORISTA URBANO	MOTORISTA URBANO SINTRAM
3039	MOTORISTA URBANO	MOTORISTA URBANO SETTRA
3000	COBRADOR URBANO	COBRADOR URBANO SETTRA
1074	AUX MONITORAMENT	AUX MONITORAMENTO
1051	AUX JURIDICO I	AUXILIAR JURIDICO I
1047	MED EXAMINADOR	MEDICO EXAMINADOR
532	MED EXAMINADOR	MEDICO EXAMINADOR
329	MED EXAMINADOR	MEDICO EXAMINADOR
4478	JOVEM APRENDIZ A	JOVEM APRENDIZ MANUTENCAO
4464	SUPERV MANUT SR	SUPERVISOR DE MANUTENÇÃO SENIOR
4457	AUX GP² IV	AUXILIAR DE PESSOAS E PERFORMANCE IV
4456	SUPERV MANUT PL	SUPERVISOR DE MANUTENÇÃO PLENO
4454	ANL ADM III	ANALISTA ADMINISTRATIVO III
4409	SUPERV FATUR III	SUPERVISOR DE FATURAMENTO III
4216	ANL QUALIDADE V	ANALISTA DE QUALIDADE V
4213	ANL QUALIDADE II	ANALISTA DE QUALIDADE II
1014	AUX DE RH I	AUXILIAR DE RH I
863	TEC ENF TRAB I	TEC ENFERMAGEM DO TRABALHO ASSISTENTE I
594	CONTROLLER	CONTROLLER
561	BORRAC ALINH IV	BORRACHEIRO ALINHADOR IV
545	ASS RH V	ASSISTENTE DE RH V
538	MED EXAMINADOR	MEDICO EXAMINADOR
491	ASS RH	ASSISTENTE DE RH
4495	AUX MONIT IV	AUXILIAR DE MONITRAMENTO IV
4451	MOTORISTA HOR	MOTORISTA HORISTA
3973	ANL TESOURARIA I	ANALISTA TESOURARIA I
3930	ADV SENIOR	ADV SENIOR
3787	AUX MONIT III	AUXILIAR DE MONITORAMENTO III
3574	MECANICO II	MECANICO II
3480	AUX TESOURARIA	AUX TESOURARIA
3261	AUX MONITORAMENT	AUX MONITORAMENT
3088	ENG SEG TRABALHO	ENGENHEIRO DE SEGURANCA DO TRABALHO
3032	JOVEM APRENDIZ	JOVEM APRENDIZ
1056	AUX MONIT I	AUXILIAR DE MONITORAMENTO I
1018	COBRADOR URB	COBRADOR URBANO SETTRA
1017	MOTORISTA URB	MOTORISTA URBANO SETTRA
983	AUX MONIT II	AUXILIAR DE MONITORAMENTO II
528	AUX TESOU I	AUXILIAR DE TESOURARIA I
522	JOVEM APRENDIZ	JOVEM APRENDIZ
506	MOTORISTA URB	MOTORISTA URBANO SINTRAM
480	COBRADOR URB	COBRADOR URBANO SINTRAM
464	COBRADOR UBERLAN	COBRADOR UBERLANDIA
463	MOTORISTA UBERL	MOTORISTA UBERLANDIA
400	AUX MONIT	AUXILIAR DE MONITORAMENTO
4494	ANL MANUT V	ANALISTA DE MANUTENCAO V
4491	ENC PATIO	ENCARREGADO DE PATIO
4487	ANL MANUT IV	ANALISTA DE MANUTENCAO IV
4479	ENC ALMOX III	ENCARREGADO DE ALMOXARIFADO III
4477	SERV GERAIS	SERV GERAIS
4476	ANL SOLICITACAO	ANALISTA DE SOLICITAÇÃO I
4470	VARREDOR I	VARREDOR DE ONIBUS
4469	VARREDOR	VARREDOR DE ONIBUS
4466	COORD ENCOMENDAS	COORDENADOR DE ENCOMENDAS
4465	ASS DE ENCOM I	ASSISTENTE DE ENCOMENDAS I
4461	SUPERV MANUT JR	SUPERVISOR MANUTENCAO JUNIOR
4450	AUX PLATAFORMA	AUXILIAR DE PLATAFORMA
4438	AUX TORNEARIA	AUXILIAR TORNERIA
4421	COORD ENCOM I	COORDENADOR ENCOMENDAS I
4417	ANL GARANTIA III	ANALISTA DE GARANTIA III
4415	ANL GARANTIA V	ANALISTA DE GARANTIA V
4406	ASS DE ENCOM II	ASSISTENTE DE ENCOMENDAS II
4393	ANL GARANTIA IV	ANL DE GARANTIA IV
4392	ASS DE GARANTIA	ASS DE GARANTIA
4391	AUX DE GARANTIA	AUX DE GARANTIA
4388	COORD TRAFEG	COORD TRAF
4384	AUX MEC INJEC	AUXILIAR MECANICO DE INJECAO
4383	REPOSITOR OLEO	REPOSITOR DE OLEO
4381	AUX OPERACOES	AUXILIAR DE OPERACOES
4380	SUPERV MANUT III	SUPERVISOR DE MANUTENCAO III
4359	COORD MONIT II	COORDENADOR DE MONITORAMENTO II
4332	AUX ELETRONI I	AUXILIAR DE ELETRONICA I
4198	COORD BILHETE IV	COORDENADOR DE BILHETERIA IV
4197	INSTR AUX VIAGEM	INSTRUTOR DE AUXILIAR DE VIAGEM
4190	ASS BILHETE III	ASSISTENTE DE BILHETERIA III
4189	MOTORISTA FRET	MOTORISTA FRETAMENTO
4109	LUBRIFICADOR	LUBRIFICADOR
3963	ENC TRAFEGO I	ENC TRAFEGO I
3789	ENC DE CARGAS	ENCARREGADO DE CARGAS
2905	ANL BILHETAG I	ANALISTA BILHETAGEM I
2074	ASS BILHETE II	ASSISTENTE DE BILHETERIA II
1073	ENC TRAFEGO II	ENCARREGADO DE TRAFEGO II
1069	COORD MANUT II	COORDENADOR DE MANUTENCAO II
1061	SUPERV BORRACH I	SUPERVISOR BORRACHARIA
1054	COORD MANUT	COORDENADOR DE MANUTENCAO
1053	COORD MANUT III	COORDENADOR MANUTENCAO III
1052	AUDITOR ALMOX II	AUDITOR DE ALMOXARIFADO II
1044	AUX SOLDADOR	AUXILIAR SOLDADOR
1041	ZELADOR	ZELADOR
1037	AUX CAPOTEIRO	AUXILIAR CAPOTEIRO
1022	COORD FISCAL III	COORDENADOR DE FISCALIZAÇÃO III
1021	AUDIT FISCAL	AUDITOR DE FISCALIZACAO
1015	ANL SEG PATR III	ANALISTA SEGURANCA PATRIMONIAL III
1012	AUDIT BORRACH  I	AUDITOR DE BORRACHARIA II
1003	ASS VENDAS V	ASSISTENTE DE VENDAS V
1002	ASS VENDAS II	ASSISTENTE DE VENDAS II
970	SUPERV TRAFE III	SUPERVISOR TRAFEGO III
969	MOTORISTA PART	MOTORISTA PARTICULAR
965	ANL COMERCIAL I	ANALISTA COMERCIAL I
920	COORD SEG I	COORDENADOR DE  SEGURANCA I
919	SEGURANCA	SEGURANCA
912	PORTEIRO A	PORTEIRO A
908	ASS VENDAS I	ASSISTENTE DE VENDAS I
905	AJUDANTE GERAL	AJUDANTE GERAL
904	ENC MANOBRIST II	ENCARREGADO MANOBRISTA II
847	BILHETEIRO URB	BILHETEIRO URBANO
845	ENC GARAGEM I	ENCARREGADO GARAGEM I
837	FISCAL URBANO	FISCAL URBANO
836	ENC GARAGEM II	ENCARREGADO DE GARAGEM
712	TORNEIRO MEC A	TORNEIRO MECANICO A
709	COORD BILHET III	COORDENADOR DE BILHETERIA III
708	COORD BILHETE II	COORDENADOR DE BILHETERIA II
707	CAPOTEIRO A	CAPOTEIRO A
706	MECANICO D	MECANICO D
700	MECANICO C	MECANICO C
696	AUX MECANICO A	AUXILIAR MECANICO A
695	COORD FISCAL I	COORDENADOR DE FISCALIZACAO I
694	COORD BILHETA II	COORDENADOR DE BILHETAGEM II
693	ENC MANUT C	ENCARREGADO MANUTENCAO C
692	COORD MONIT I	COORDENADOR DE MONITORAMENTO I
691	MOTORISTA INSTR	MOTORISTA INSTRUTOR I
690	ENC MANUT B	ENCARREGADO MANUTENCAO B
689	SERV PEDREIRO A	SERVENTE PEDREIRO A
686	MECANICO A	MECANICO A
684	MEC MONTADOR A	MECANICO MONTADOR A
683	LANTERNEIRO A	LANTERNEIRO A
682	ENC PINTURA A	ENCARREGADO PINTURA A
674	ENC BORRACH A	ENCARREGADO DE BORRACHARIA A
671	AUX CONT MANUT	AUXILIAR CONTROLADOR DE MANUTENCAO
669	SUPERV TRAFEG I	SUPERVISOR TRAFEGO I
668	SUPERV TRAFEG II	SUPERVISOR TRAFEGO II
667	COORD MONIT III	COORDENADOR MONITORAMENTO III
666	MEC INJECAO IV	MECANICO DE INJECAO IV
665	MEC INJECAO III	MECANICO DE INJECAO III
664	MEC INJECAO II	MECANICO DE INJECAO II
663	MEC INJECAO I	MECANICO DE INJECAO I
660	MEC MONTADOR IV	MECANICO MONTADOR IV
659	SUPERV MANUT II	SUPERVISOR MANUTENCAO II
657	AUDIT MANUT II	AUDITOR DE MANUTENCAO II
656	AUD MANUT I	AUDITOR DE MANUTENCAO I
645	ENC SERV GER II	ENCARREGADO SERVICOS GERAIS II
644	ENC ALMOX II	ENCARREGADO ALMOXARIFADO II
643	MONTADOR RAD III	MONTADOR RADIADOR III
642	MONTADOR RAD II	MONTADOR RADIADOR II
641	MONTADOR RAD I	MONTADOR RADIADOR I
640	AUX MONT RAD	AUXILIAR MONTADOR RADIADOR
639	MECANICO IND V	MECANICO INDUSTRIAL V
638	ENC USINAGEM II	ENCARREGADO USINAGEM II
637	ENC INJECAO II	ENCARREGADO MECANICO DE INJECAO II
636	ENC INJECAO I	ENCARREGADO MECANICO DE INJECAO I
635	MEC INJECAO V	MECANICO DE INJECAO V
633	ENC PNEUMAT II	ENCARREGADO MECANICO PNEUMATICO II
632	ENC MEC PNEUM I	ENCARREGADO MECANICO PNEUMATICO I
628	ENC CAPOTARIA II	ENCARREGADO CAPOTARIA II
627	PINTOR LETR IV	PINTOR LETRISTA IV
626	AUX PINTOR LET	AUXILIAR PINTOR LETRISTA
625	ENC PINTURA II	ENCARREGADO PINTURA II
624	ENC LANTERN II	ENCARREGADO LANTERNEIRO II
622	ENC ELETRICA II	ENCARREGADO ELETRICA II
621	ELETRIC TAC V	ELETRICISTA TACOGRAFISTA V
620	ELETRIC TAC IV	ELETRICISTA TACOGRAFISTA IV
619	ELETRIC TAC II	ELETRICISTA TACOGRAFISTA II
618	ELETRIC TAC I	ELETRICISTA TACOGRAFISTA I
615	TEC ELETRON V	TECNICO ELETRONICA V
614	AUX TEC ELETRO I	AUXILIAR TECINICO ELETRONICA I
613	AUX TEC ELETRON	AUXILIAR TECNICO ELETRONICA
612	CONTR PNEUS V	CONTROLADOR DE PNEUS V
611	ENC BORRACH II	ENCARREGADO DE BORRACHARIA II
610	ENC BORRACH I	ENCARREGADO DE BORRACHARIA I
609	VIGIA	VIGIA
608	CONF VEICULOS	CONFERENTE DE VEICULOS
606	CONTR PNEUS IV	CONTROLADOR DE PNEUS IV
603	AGENTE ESTACAO	AGENTE DE ESTACAO
601	MONTADOR RAD V	MONTADOR DE RADIADOR V
593	ELETRIC TAC III	ELETRICISTA TACOGRAFISTA III
541	TEC ELETRON IV	TECNICO ELETRONICA IV
377	AUX MEC PNEUMAT	AUXILIAR DE MECANICO PNEUMATICO
370	AUX CONT PNEUS	AUXILIAR CONTROLADOR DE PNEUS
369	CONTR PNEUS III	CONTROLADOR DE PNEUS III
4493	GER REG MANUT	GERENTE REGIONAL DE MANUTENÇÃO
4492	GER GP² IV	GERENTE DE GESTAO, PESSOAS E PERFORMANCE IV
4490	ASS SUPRIMENTO I	ASSISTENTE DE SUPRIMENTOS I
4489	ANL SUPRIMENTO I	ANALISTA DE SUPRIMENTOS I
4488	ADVOGADO PL IV	ADVOGADO PLENO IV
4485	AUX GP² I	AUXILIAR DE PESSOAS E PERFORMANCE I
4484	ANL TI V A	ANALISTA DE TI V
4483	ANL ALMOXARIFE I	ANALISTA DE ALMOXARIFADO I
4481	ASS SINISTRO V	ASSISTENTE SINISTRO V
4475	SUPERV GP² IV	SUPERVISOR DE PESSOAS E PERFORMANCE IV
4474	ASS MONIT I	ASSISTENTE DE MONITORAMENTO I
4473	ANL GP² IV	ANALISTA DE PESSOAS E PERFORMANCE IV
4472	ANL REVENUE IV	ANALISTA DE REVENUE IV
4471	SUP CONTROL II	SUPERV CONTROLADORIA  II
4468	SUPERV PESSOA IV	SUPERV PESSOA IV
4467	COORD REG MANUT	COORDENADOR REGINAL DE MANUTENÇÃO
4463	SUPERV DESENV II	SUPERVISOR DESENVOLVIMENTO DE SISTEMA II
4462	ANL FISCAL III	ANALISTA FISCAL III
4459	GER FINANC II	GERENTE FINANCEIRO II
4458	ASS GP² IV	ASSISTENTE DE PESSOAS E PERFORMANCE IV
4455	SUPERV GP² II	SUPERVISOR DE PESSOAS E PERFORMANCE II
4453	ASS MONIT IV	ASSISTENTE DE MONITORAMENTO IV
4452	GER COMPRAS III	GERENTE COMPRAS III
4449	ASS GP² III	ASSISTENTE DE PESSOAS E PERFORMANCE III
4448	AUX GP² V	AUXILIAR DE PROJETOS E PROCESSOS V
4444	ANL GP² III	ANALISTA DE PROJETOS E PROCESSOS III
4443	ASS GP² I	ASSISTENTE DE PESSOAS E PROCESSOS I
4442	ANL GP² IV	ANALISTA DE PESSOAS E PERFORMANCE IV
4441	ASS GP² I	ASSISTENTE DE PESSOAS E PERFORMANCE I
4440	AUX GP² III	AUXILIAR DE PESSOAS E PERFORMANCE III
4439	ANL GP² I	ANALISTA DE PESSOAS E PERFORMANCE I
4437	GER GP² III	GERENTE DE GESTAO, PESSOAS E PERFORMANCE
4436	AUX DE GP² V	AUXILIAR DE PESSOAS E PERFORMANCE V
4434	SUPERV PESSO III	SUPERVISOR PESSOAL III
4433	SUPERV GP2 I	SUPERVISOR DE PESSOAS E PEFORMANCE I
4432	SUPERV CONTR II	SUPERVISOR DE CONTRATOS II
4431	SUPERV FINAN III	SUPERVISOR FINANCEIRO III
4428	SUPERV PESSOA II	SUPERVISOR PESOSAL II
4427	COORD CONTR III	COORDENADOR DE CONTROLADORIA III
4425	SUPERV CUSTOS II	SUPERVISOR DE CUSTOS II
4424	SUPERV FINANC II	SUPERVISOR FINANCEIRO II
4420	GER FINANÇAS	GER FINANÇAS
4419	SUPERV CONTAB II	SUPERVISOR CONTABIL II
4418	GER PROJETOS I	GERENTE DE PROJETOS I
4414	COORD COMERC I	COORDENADOR COMERCIAL I
4413	COORD PROJET III	COORDENADOR DE PROJETOS III
4404	GER TRAINEE	GERENTE TRAINEE
4394	ANL FISCAL IV	ANALISTA FISCAL IV
4389	TEC SAUDE OCUP	TECNICO SAUDE OCUPACIONAL
4386	AUX FISCAL	AUXILIAR FISCAL
4379	ANL SEG TRAB I	ANALISTA SEGURANCA DO TRABALHO I
4377	ANL CONTRATOS II	ANALISTA DE CONTRATOS II
4376	COORD AMBIENT II	COORDENADOR AMBIENTAL II
4375	ASS FISCAL II	ASSISTENTE FISCAL II
4374	AUX FISCAL II	AUXILIAR FISCAL II
4373	ANL FISCAL I	ANALISTA FISCAL I
4372	AUDITOR ALMOX I	AUDITOR ALMOXARIFADO I
4368	ASS TST V	TECNICO DE SEGURANCA DO TRABALHO V ASSISTENTE
4367	ASS TST IV	TECNICO DE SEGURANCA DO TRABALHO IV ASSISTENTE
4366	ASS TST III	TECNICO DE SEGURANCA DO TRABALHO III ASSISTENTE
4365	ASS TST II	TECNICO DE SEGURANCA DO TRABALHO II ASSISTENTE
4364	ASS TST I	TECNICO DE SEGURANCA DO TRABALHO I ASSISTENTE
4234	ANL FROTA V	ANALISTA DE FROTA V
4233	ANL FROTA IV	ANALISTA DE FROTA IV
4232	ANL FROTA III	ANALISTA DE FROTA III
4231	ANL FROTA II	ANALISTA DE FROTA II
4230	ANL FROTA I	ANALISTA DE FROTA I
4229	ANL FATURAM V	ANALISTA DE FATURAMENTO V
4228	ANL FATURAM IV	ANALISTA DE FATURAMENTO IV
4227	ANL FATURAM II	ANALISTA DE FATURAMENTO II
4226	ANL DOCUMENT V	ANALISTA DE DOCUMENTOS V
4225	ANL DOCUMENT IV	ANALISTA DE DOCUMENTOS IV
4224	ANL DOCUMENT II	ANALISTA DE DOCUMENTOS II
4223	ANL DOCUMENT I	ANALISTA DE DOCUMENTOS I
4222	ANL CONFER IV	ANALISTA DE CONFERENCIA IV
4221	ANL CONFER III	ANALISTA DE CONFERENCIA III
4220	ANL CONFER II	ANALISTA DE CONFERENCIA II
4219	ANL CONFER I	ANALISTA DE CONFERENCIA I
4218	ANL COMPRAS V	ANALISTA DE COMPRAS V
4217	ANL COMPRAS IV	ANALISTAS DE COMPRAS IV
4215	ANL QUALIDADE IV	ANALISTA DE QUALIDADE IV
4214	ANL QUALID III	ANALISTA DE QUALIDADE III
4212	ANL QUALIDADE I	ANALISTA DE QUALIDADE I
4211	ANL CONTABIL V	ANALISTA CONTABIL V
4210	ANL CONTABIL IV	ANALISTA CONTABIL IV
4209	ANL CONTABIL III	ANALISTA CONTABIL III
4208	ANL CONTABIL I	ANALISTA CONTABIL I
4207	ANL COMERC V	ANALISTA COMERCIAL V
4206	ANL COMERC IV	ANALISTA COMERCIAL IV
4205	ANL COMERC III	ANALISTA COMERCIAL III
4204	ANL COMERC II	ANALISTA COMERCIAL II
4202	ANL AMBIENT III	ANALISTA AMBIENTAL III
4201	ANL AMBIENT II	ANALISTA AMBIENTAL II
4200	ADVOGADO SR II	ADVOGADO SENIOR II
4195	ANL OPERACOES I	ANALISTA DE OPERACOES I
4194	ASS FROTA I	ASSISTENTE DE FROTA I
4193	ANL OPERAC JR	ANALISTA DE OPERACOES JR
4192	SUPERV FROTA II	SUPERVISOR DE FROTA
4191	SUPERV OPERAC II	SUPERVISOR DE OPERACOES II
4188	AUX  QUALIDADE I	AUX QUALIDADE I
4187	ASS PROJETOS V	ASSISTENTE PROJETOS E PROCESSOS V
4184	ASS SINISTRO I	ASSISTENTE SINISTRO I
4181	SUPERV PROJETOS	SUPERVISOR DE PROJETOS II
4177	AUX FATURAMENTO	AUX FATURAMENTO
4176	AUX DE RH I	AUXILIAR DE RH I
4141	SUPERV CUSTO I	SUP DE CUSTOS I
4110	ANL PESSOAL III	ANALISTA DE PESSOAL III
4097	ASS RH III	ASS RH III
3730	SUPERV PESSOAL I	SUPERVISOR DE PESSOAL I
3393	ASS DIRETORIA I	ASSISTENTE DE DIRETORIA I
2908	COORD CUSTOS I	COORDENADOR DE CUSTOS
2906	ANL FATURAM III	ANALISTA DE FATURAMENTO III
2075	ASS FATURAMEN IV	ASSISTENTE FATURAMENTO IV
1070	AUX DE TI I	AUXILIAR DE TI I
1068	ANL PESSOAL I	ANALISTA PESSOAL I
1067	AUX FINANCEIRO	AUXILIAR FINANCEIRO
1066	AUXILIAR RH II	AUXILIAR DE RH II
1065	AUX SINISTRO III	AUXILIAR DE SINISTRO III
1064	ASS COMP I	ASSISTENTE DE COMPRAS I
1063	ANL CONTROL V	ANALISTA CONTROLADORIA V
1062	ANL FINANC IV	ANALISTA FINANCEIRO IV
1060	AUX BILHETAG V	AUXILIAR BILHETAGAGEM V
1059	ANL DESENV III	ANALISTA DE DESENVOLVIMENTO DE SISTEMAS III
1058	ANL TEC ENF T II	TEC ENF TRAB II ANALISTA
1057	GER AUDITORIA I	GERENTE DE AUDITORIA I
1055	AUX SERV MED	AUXILIAR DE SERVICOS MEDICOS
1046	ASS QUALIDADE V	ASSISTENTE DE QUALIDADE V
1045	TEC EDIFICACOES	TECNICO EM EDIFICACOES
1043	ASS TI I	ASSISTENTE TI I
1040	SUPERV BILHETAG	SUPERVISOR DE BILHETAGEM I
1039	ASS SINISTRO II	ASSISTENTE SINISTRO II
1038	GERENTE QUALID	GERENTE DA QUALIDADE
1035	ASS TESOUR V	ASSISTENTE TESOURARIA V
1034	ASS ADM V	ASSISTENTE ADMINISTRATIVO V
1033	ANL PROJETOS IV	ANALISTA PROJETOS E PROCESSOS IV
1032	ASS DESENV III	ASSISTENTE DE DESENVOLVIMENTO DE SISTEMAS III
1031	ANL MARKETING II	ANALISTA DE MARKETING II
1030	ADVOGADO JR III	ADVOGADO JUNIOR III
1029	AUX JURIDICO III	AUXILIAR JURIDICO III
1026	AUX SERV MED IV	AUXILIAR DE SERVICOS MEDICO IV
1025	AUX SERV MED V	AUXILIAR DE SERVICOS MEDICO V
1024	TEC ENF TRAB I	TEC ENFERMAGEM DO TRABALHO ANALISTA I
1023	AUX CONFERENCIA	AUXILIAR DE CONFERENCIA
1019	ANL ADM II	ANALISTA ADMINISTRATIVO II
1013	AUX CONFEREN I	AUXILIAR DE CONFERENCIA I
1011	ANL AMBIENT IV	ANALISTA AMBIENTAL IV
1010	SUPERV CONFER II	SUPERVISOR DE CONFERENCIA II
1009	ANL TESOUR III	ANALISTA TESOURARIA III
1008	GERENTE AMBIENT	GERENTE DE MEIO AMBIENTE
1006	ANL ADM I	ANALISTA ADMINISTRATIVO
1005	ASS TESOUR I	ASSISTENTE TESOURARIA I
1004	ASS BILHETAG III	ASSISTENTE DE BILHETAGEM III
1001	ANL TST V	TEC SEGURANCA DO TRABALHO V ANALISTA
999	ANL TST IV	TEC SEGURANCA DO TRABALHO IV ANALISTA
998	ANL TST III	TEC SEGURANCA DO TRABALHO III ANALISTA
997	ANL TST II	TEC SEGURANCA DO TRABALHO II ANALISTA
996	ANL TST I	TEC SEGURANCA DO TRABALHO I ANALISTA
995	AUX TST V	TEC SEGURANCA DO TRABALHO V AUXILIAR
994	AUX TST IV	TEC SEGURANCA DO TRABALHO IV AUXILIAR
993	AUX TST III	TEC SEGURANCA DO TRABALHO III AUXILIAR
992	AUX TST II	TEC SEGURANCA DO TRABALHO II AUXILIAR
991	AUX TST I	TEC SEGURANCA DO TRABALHO I AUXILIAR
990	ASS QUALIDADE II	ASSISTENTE DE QUALIDADE II
988	AUX DE TI III	AUXILIAR DE TI III
987	ASS TESOUR IV	ASSISTENTE TESOURARIA IV
986	ASS TESOUR II	ASSISTENTE TESOURARIA II
985	AUX DE SAC I	AUXILIAR DE SAC I
984	ASS SAC II	ASSISTENTE DE SAC II
982	ASS FINANC IV	ASSISTENTE FINANCEIRO IV
979	ASS DOCUMENT IV	ASSISTENTE DOCUMENTOS IV
978	ANL PESSOAL IV	ANALISTA DE PESSOAL IV
975	ASS DOCUMENT II	ASSISTENTE DOCUMENTOS II
974	ANL DOCUMENT III	ANALISTA DOCUMENTOS III
972	ANL SINISTRO I	ANALISTA SINISTRO I
971	AUX JURIDICO IV	AUXILIAR JURIDICO IV
967	SUPERV ESTATISTI	SUPERVISOR DE ESTATISTICA
964	ASS BILHETAG V	ASSISTENTE BILHETAGEM V
963	ANL TESOUR IV	ANALISTA TESOURARIA IV
962	ANALISTA TI IV	ANALISTA TI IV
961	ANL COMPRAS II	ANALISTA COMPRAS II
960	ANL CONTABIL I	ANALISTA CONTABIL I
959	ASS CONTABIL II	ASSISTENTE CONTABIL II
958	ASS CONTABIL V	ASSISTENTE CONTABIL V
957	ASS CONTABIL IV	ASSISTENTE CONTABIL IV
956	GER COMERCIAL	GERENTE COMERCIAL
955	GER FINANCEIRO	GERENTE FINANCEIRO
954	ANL FINANC II	ANALISTA FINANCEIRO II
952	AUX FINANC V	AUXILIAR FINANCEIRO V
951	ASS FINANC V	ASSISTENTE FINANCEIRO V
950	ANL FINANC I	ANALISTA FINANCEIRO I
949	COORD FINANC I	COORDENADOR FINANCEIRO I
948	ASS FINANC III	ASSISTENTE FINANCEIRO III
947	COORDENADOR TI	COORDENADOR TI
946	SUPERV DESENV I	SUPERVISOR DESENVOLVIMENTO DE SISTEMA I
945	ASS TI V	ASSISTENTE TI V
944	ASS CONFER III	ASSISTENTE CONFERENCIA III
943	AUX FATURAM IV	AUXILIAR FATURAMENTO IV
942	ASS FATURAM I	ASSISTENTE FATURAMENTO I
941	GER FATURAMENTO	GERENTE FATURAMENTO
940	ANL FATURAM I	ANALISTA FATURAMENTO I
937	AUX ESTATI III	AUXILIAR ESTATISTICA III
934	ASS CONFER I	ASSISTENTE CONFERENCIA I
933	AUX CONFER V	AUXILIAR CONFERENCIA V
932	AUX CONFER IV	AUXILIAR CONFERENCIA IV
931	ANL TESOUR V	ANALISTA TESOURARIA V
930	ANL CONFER V	ANALISTA DE CONFERENCIA V
929	ASS CONFER V	ASSISTENTE CONFERENCIA V
928	AUX CONFER III	AUXILIAR DE CONFERENCIA III
926	SUPERV COMPRAS I	SUPERVISOR COMPRAS
924	ANL COMPRAS I	ANALISTA COMPRAS I
923	COORD COMPRAS	COORDENADOR COMPRAS
922	ASS COMP II	ASSISTENTE DE COMPRAS II
921	ANL COMP III	ANALISTA COMPRAS III
917	ASS CUSTOS V	ASSISTENTE CUSTOS V
916	AUDIT QUALIDADE	AUDITOR QUALIDADE
915	ASS CUSTOS III	ASSISTENTE CUSTOS III
907	AUX FATURAME III	AUXILIAR FATURAMENTO III
902	ANL TESOUR II	ANALISTA TESOURARIA II
900	ASS TESOUR III	ASSISTENTE TESOURARIA III
898	ASSESSOR	ASSESSOR
897	ASSESSORA	ASSESSORA
895	ANL TESOUR I	ANALISTA TESOURARIA I
894	ASSES IMPRENSA	ASSESSORA IMPRENSA
890	COORD PLANEJA II	COORDENADOR DE PLANEJAMENTO
889	ANL CUSTOS IV	ANALISTA CUSTO IV
888	COORD PESSOAL II	COORDENADOR DEPARTAMENTO PESSOAL II
887	COORD PESSOAL I	COORDENADOR DEPARTAMENTO PESSOAL I
886	COORD RH II	COORDENADOR RH II
881	COORD JURIDIC II	COORDENADOR JURIDICO CIVEL II
880	ASS JURIDICO I	ASSISTENTE JURIDICO I
878	GERENTE JURIDICO	GERENTE JURIDICO ADMINISTRATIVO
877	ADVOGADO COORD	ADVOGADO COORDENADOR
876	ADVOGADO SR I	ADVOGADO SENIOR I
873	ADVOGADO SR III	ADVOGADO SENIOR III
872	ASS JURIDICO III	ASSISTENTE JURIDICO III
870	ANL JURIDICO III	ANALISTA JURIDICO III
869	AUX JURIDICO V	AUXILIAR JURIDICO V
868	ADVOGADO PL III	ADVOGADO PLENO III
867	ANL JURIDICO I	ANALISTA JURIDICO I
866	AUX JURIDICO I	AUXILIAR JURIDICO I
865	AUX JURIDICO II	AUXILIAR JURIDICO II
864	ASS JURIDICO IV	ASSISTENTE JURIDICO IV
860	AUX SERV MED I	AUXILIAR DE SERVICOS MEDICO I
859	ANL SERV MED I	ANALIISTA SERVICO MEDICO I
857	ANL RH V	ANALISTA RH V
856	ASS SERV MED IV	ASSISTENTE DE SERVICOS MEDICO IV
855	AUX SERV MED III	AUXILIAR DE SERVICOS MEDICO III
854	AUX SERV MED II	AUXILIAR DE SERVICOS MEDICO II
853	ASS PESSOAL V	ASSISTENTE PESSOAL V
852	ANL PESSOAL II	ANALISTA PESSOAL II
851	ASS PESSOAL IV	ASSISTENTE PESSOAL IV
850	ASS PESSOAL I	ASSISTENTE DE PESSOAL I
849	ASS PESSOAL III	ASSISTENTE PESSOAL III
604	AUX BILHETAG I	AUXILIAR DE BILHETAGEM I
597	ADVOGADO JR II	ADVOGADO JUNIOR II
596	ADV JUNIOR I	ADVOGADO JUNIOR I
595	ADVOGADO PL II	ADVOGADO PLENO II
592	COORD BILHETAG I	COORDENADOR DE  BILHETAGEM I
544	ASS SERV MED III	ASSISTENTE DE SERVICO MEDICO III
539	AUX BILHETAG II	AUXILIAR DE BILHETAGEM II
4363	GER CONTABIL	GERENTE DE CONTABILIDADE
4362	GER COMPRAS	GERENTE DE COMPRAS
4358	AUXILIAR TI V	AUXILIAR DE TI V
4357	AUX TI IV	AUXILIAR DE TI IV
4356	AUXILIAR TI II	AUXILIAR DE TI II
4354	AUX SINISTRO II	AUXILIAR DE SINISTRO II
4353	AUX SINISTRO I	AUXILIAR DE SINISTRO I
4351	AUX SAC IV	AUXILIAR DE SAC IV
4350	AUX SAC III	AUXILIAR DE SAC III
4348	AUX RH V	AUXILIAR DE RH V
4347	AUX RH IV	AUXILIAR DE RH IV
4346	AUX RH III	AUXILIAR DE RH III
4345	AUX OPERAC V	AUXILIAR DE OPERACOES V
4344	AUX OPERAC IV	AUXILIAR DE OPERACOES IV
4343	AUX OPERAC III	AUXILIAR DE OPERACOES III
4342	AUX OPERAC II	AUXILIAR DE OPERACOES II
4341	AUX OPERAC I	AUXILIAR DE OPERACOES I
4340	AUX DE FROTA V	AUXILIAR DE FROTA V
4339	AUX FROTA IV	AUXILIAR DE FROTA IV
4338	AUX FROTA III	AUXILIAR DE FROTA III
4337	AUX FROTA II	AUXILIAR DE FROTA II
4336	AUX FROTA I	AUXILIAR DE FROTA I
4335	AUX FATURAM V	AUXILIAR DE FATURAMENTO V
4334	AUX FATURAM II	AUXILIAR DE FATURAMENTO II
4333	AUX FATURAM I	AUXILIAR DE FATURAMENTO I
4329	AUX BILHETAG IV	AUXILIAR DE BILHETAGEM IV
4328	AUX BILHETAG III	AUXILIAR DE BILHETAGEM III
4327	AUX QUALIDADE V	AUXILIAR DA QUALIDADE V
4326	AUX QUALIDADE IV	AUXILIAR DA QUALIDADE IV
4325	AUX QUALID III	AUXILIAR DA QUALIDADE III
4324	AUX QUALIDADE II	AUXILIAR DA QUALIDADE II
4323	AUX QUALIDADE I	AUXILIAR DA QUALIDADE I
4322	AUX COMERC V	AUXILIAR COMERCIAL V
4321	AUX COMERC III	AUXILIAR COMERCIAL II
4319	ASS JURIDICO V	ASSISTENTE JURIDICO V
4317	ASSISTENTE TI IV	ASSISTENTE DE TI IV
4316	ASS TI III	ASSISTENTE DE TI III
4315	ASSISTENTE TI II	ASSISTENTE DE TI II
4309	ASS SERV MED V	ASSISTENTE DE SERVICOS MEDICOS V
4308	ASS SERV MED II	ASSISTENTE DE SERVICOS MEDICOS II
4307	ASS SERV MED I	ASSISTENTE DE SERVICOS MEDICOS I
4306	ASS SAC V	ASSISTENTE DE SAC V
4305	ASS SAC IV	ASSISTENTE DE SAC IV
4304	ASS SAC III	ASSISTENTE DE SAC III
4303	ASS SAC I	ASSISTENTE DE SAC I
4302	ASSISTENTE RH V	ASSISTENTE DE RH V
4301	ASSISTENTE RH IV	ASSISTENTE DE RH IV
4300	ASS PROJETOS IV	ASSISTENTE DE PROJETOS E PROCESSOS IV
4299	ASS PROJETOS III	ASSISTENTE DE PROJETOS E PROCESSOS III
4298	ASS PROJETOS II	ASSISTENTE DE PROJETOS E PROCESSOS II
4297	ASS PROJETOS I	ASSISTENTE DE PROJETOS E PROCESSOS I
4296	ASS OPERAC V	ASSISTENTE DE OPERACOES V
4295	ASS OPERAC IV	ASSISTENTE DE OPERACOES IV
4294	ASS OPERAC III	ASSISTENTE DE OPERACOES III
4293	ASS OPERAC II	ASSISTENTE DE OPERACOES II
4292	ASS OPERAC I	ASSISTENTE DE OPERACOES I
4291	ASS FROTA V	ASSISTENTE DE FROTA V
4290	ASS FROTA IV	ASSISTENTE DE FROTA IV
4288	ASS FROTA II	ASSISTENTE DE FROTA II
4287	ASS FATURAM V	ASSISTENTE DE FATURAMENTO V
4286	ASS FATURAM III	ASSISTENTE DE FATURAMENTO III
4285	ASS FATURAM II	ASSISTENTE DE FATURAMENTO II
4284	ASS DOCUMENT III	ASSISTENTE DE DOCUMENTOS III
4283	ASS DOCUMENT I	ASSISTENTE DE DOCUMENTOS I
4282	ASS CUSTOS IV	ASSISTENTE DE CUSTOS IV
4281	ASS CUSTOS II	ASSISTENTE DE CUSTOS II
4278	ASS CONFER II	ASSISTENTE DE CONFERENCIA II
4277	ASS COMP V	ASSISTENTE DE COMPRAS V
4276	ASS COMP IV	ASSISTENTE DE COMPRAS IV
4275	ASS COMP III	ASSISTENTE DE COMPRASIII
4274	ASS BILHETE I	ASSISTENTE DE BILHETERIA I
4273	ASS BILHETAG IV	ASSISTENTE DE BILHETAGEM IV
4272	ASS BILHETAG II	ASSISTENTE DE BILHETAGEM II
4271	ASS BILHETAG I	ASSISTENTE DE BILHETAGEM I
4270	ASS QUALIDADE IV	ASSISTENTE DA QUALIDADE IV
4269	ASS QUALIDAD III	ASSISTENTE DA QUALIDADE III
4268	ASS QUALIDADE I	ASSISTENTE DA QUALIDADE I
4267	ASS CONTABIL III	ASSISTENTE CONTABIL III
4266	ASS COMERC V	ASSISTENTE COMERCIAL V
4265	ASS COMERC IV	ASSISTENTE COMERCIAL IV
4264	ASS COMERC III	ASSISTENTE COMERCIAL III
4263	ASS COMERC II	ASSISTENTE COMERCIAL II
4262	ASS COMERC I	ASSISTENTE COMERCIAL I
4261	ANL JURIDICO V	ANALISTA JURIDICO V
4260	ANL JURIDICO IV	ANALISTA JURIDICO IV
4259	ANL JURIDICO II	ANALISTA JURIDICO II
4258	ANL FINANC V	ANALISTA FINANCEIRO V
4257	ANL FINANC III	ANALISTA FINANCEIRO III
4256	ANL TI V	ANALISTA DE TI V
4255	ANL SINISTRO V	ANALISTA DE SINISTRO V
4254	ANL SINISTRO IV	ANALISTA DE SINISTRO IV
4253	ANL SINISTRO III	ANALISTA DE SINISTRO III
4252	ANL SINISTRO II	ANALISTA DE SINISTRO II
4251	ANL SERV MED V	ANALISTA DE SERVICOS MEDICOS V
4250	ANL SERV MED IV	ANALISTA DE SERVICOS MEDICOS IV
4249	ANL SERV MED III	ANALISTA DE SERVICOS MEDICOS III
4248	ANL SERV MED II	ANALISTA DE SERVICOS MEDICOS II
4247	ANL PROJETOS V	ANALISTA DE PROJETOS E PROCESSOS V
4246	ANL PROJETOS III	ANALISTA DE PROJETOS E PROCESSOS III
4245	ANL PROJETOS II	ANALISTA DE PROJETOS E PROCESSOS II
4244	ANL PROJETOS I	ANALISTA DE PROJETOS E PROCESSOS I
4243	ANL PESSOAL V	ANALISTA DE PESSOAL V
4242	ANL OPERAC V	ANALISTA DE OPERACOES V
4241	ANL OPERAC IV	ANALISTA DE OPERACOES IV
4240	ANL OPERAC III	ANALISTA DE OPERACOES III
4239	ANL OPERAC II	ANALISTA DE OPERACOES II
4238	ANL MARKETING V	ANALISTA DE MARKETING V
4237	ANL MARKETING IV	ANALISTA DE MARKETING IV
4236	ANL MARKETIN III	ANALISTA DE MARKETING III
4235	ANL MARKETING I	ANALISTA DE MARKETING I
2904	TORNEIRO MEC V	TORNEIRO MECANICO V
2903	TEC ELETRON II	TECNICO ELETRONICA II
2902	ENC PINTURA I	ENCARREGADO DE PINTURA I
2374	MEC MONTADOR III	MECANICO MONTADOR III
2355	MOLEIRO V	MOLEIRO V
2348	CAPOTEIRO V	CAPOTEIRO V
2254	MEC MONTADOR I	MECANICO MONTADOR I
833	AUX MONT RAD I	AUXILIAR MONTADOR RADIADOR I
831	MECANICO IND IV	MECANICO INDUSTRIAL IV
824	SOLDADOR V	SOLDADOR V
804	MEC PNEUMAT IV	MECANICO PNEUMATICO IV
803	ENC MANUT II	ENCARREGADO MANUTENCAO II
802	ENC MANUT I	ENCARREGADO MANUTENCAO I
793	AUX SOLDADOR I	AUXILIAR SOLDADOR I
588	CONTR PNEUS II	CONTROLADOR DE PNEUS II
587	CONTR PNEUS I	CONTROLADOR DE PNEUS I
577	AUX USINAGEM	AUXILIAR DE USINAGEM
571	MEC MONTADOR II	MECANICO MONTADOR II
569	AUX PINTOR LET I	AUXILIAR PINTOR LETRISTA I
568	CONTR MANUT V	CONTROLADOR DE MANUTENCAO V
567	BORRACH V	BORRACHEIRO V
566	MECANICO V	MECANICO V
556	ENC ELETRICA I	ENCARREGADO DE ELETRICA I
554	MEC PNEUMAT III	MECANICO PNEUMATICO III
552	ENC CAPOTARIA I	ENCARREGADO DE CAPOTARIA
549	ENC LANTERN I	ENCARREGADO DE LANTERNAGEM I
527	MEC PNEUMAT V	MECANICO PNEUMATICO V
525	CONTR MANUT IV	CONTROLADOR DE MANUTENCAO IV
497	MONTADOR RAD IV	MONTADOR DE RADIADOR IV
486	PINTOR V	PINTOR V
471	MEC PNEUMAT I	MECANICO PNEUMATICO I
470	MEC PNEUMAT II	MECANICO PNEUMATICO II
468	TORNEIRO MEC IV	TORNEIRO MECANICO IV
467	CAPOTEIRO IV	CAPOTEIRO IV
459	TRAB AGROPEC POL	TRABALHADOR AGROPECUARIO POLIVANTE
455	SUPERV MANUT I	SUPERVISOR MANUTENCAO I
439	ENC SERV GER I	ENCARREGADO SERVICOS GERAIS I
425	AUX MECANICA	AUXILIAR DE MECANICA
423	AUX LANTERN I	AUXILIAR DE LANTERNAGEM I
415	PINTOR LETR II	PINTOR LETRISTA II
414	PINTOR I	PINTOR I
411	CAPOTEIRO III	CAPOTEIRO III
381	ELETRICISTA V	ELETRICISTA V
378	ENC MANUT III	ENCARREGADO DE MANUTENCAO III
374	MOLEIRO III	MOLEIRO III
373	MOLEIRO IV	MOLEIRO IV
354	CONTR MANUT III	CONTROLADOR DE MANUTENCAO III
352	AUX MEC IND	AUXILIAR MECANICO INDUSTRIAL
348	AUX MEC IND I	AUXILIAR MECANICO INDUSTRIAL I
344	ENC USINAGEM I	ENCARREGADO DE USINAGEM I
341	CONTR MANUT II	CONTROLADOR DE MANUTENCAO II
336	MECANICO IND I	MECANICO INDUSTRIAL I
331	SOLDADOR IV	SOLDADOR IV
326	LANTERNEIRO V	LANTERNEIRO V
315	TEC ELETRON III	TECNICO EM ELETRONICA III
313	SOLDADOR II	SOLDADOR II
279	BORRACH III	BORRACHEIRO III
260	PINTOR LETR I	PINTOR LETRISTA I
254	AUX USINAGEM I	AUXILIAR DE USINAGEM I
239	AUX ELETRICA I	AUXILIAR DE ELETRICA I
216	LANTERNEIRO III	LANTERNEIRO III
213	PINTOR IV	PINTOR IV
210	TORNEIRO MEC III	TORNEIRO MECÂNICO III
209	TORNEIRO MEC II	TORNEIRO MECÂNICO II
208	TORNEIRO MEC I	TORNEIRO MECÂNICO I
197	SOLDADOR I	SOLDADOR I
191	BORRACH IV	BORRACHEIRO IV
181	AUX MOLEIRO I	AUXILIAR DE MOLEIRO I
179	LUBRIFICADOR	LUBRIFICADOR
177	PINTOR III	PINTOR III
172	AUX BORRACH	AUXILIAR DE BORRACHARIA
164	AUX BORRACH I	AUXILIAR DE BORRACHARIA I
161	MOLEIRO I	MOLEIRO I
149	AUX LANTERN	AUXILIAR DE LANTERNAGEM
148	AUX ELETRICA	AUXILIAR DE ELÉTRICA
141	MANOBRISTA	MANOBRISTA
129	ELETRICISTA I	ELETRICISTA I
125	MOLEIRO II	MOLEIRO II
121	SERV GERAIS	SERVICOS GERAIS
119	CAPOTEIRO II	CAPOTEIRO II
117	AUX CAPOTEIRO I	AUXILIAR DE CAPOTEIRO I
97	SERVENT PEDREIRO	SERVENTE DE PEDREIRO
92	BORRACH II	BORRACHEIRO II
91	ENC MANOBRISTA I	ENCARREGADO DE MANOBRA I
84	ALMOXARIFE I	ALMOXARIFE I
79	SOLDADOR III	SOLDADOR III
72	ELETRICISTA II	ELETRICISTA II
62	FRENTISTA	FRENTISTA
58	MECANICO IND III	MECANICO INDUSTRIAL III
57	MEC INDUSTRIA II	MECANICO INDUSTRIAL II
48	CONTR MANUT I	CONTROLADOR MANUTENCAO I
47	PINTOR LETR III	PINTOR LETRISTA III
36	AUX MOLEIRO	AUXILIAR DE MOLEIRO
34	LANTERNEIRO IV	LANTERNEIRO IV
32	MECANICO IV	MECANICO IV
31	LANTERNEIRO I	LANTERNEIRO I
27	MECANICO II	MECANICO II
26	MECANICO III	MECANICO III
25	PINTOR II	PINTOR II
24	AUX MECANICA I	AUXILIAR MECANICA I
23	AUX PINTURA I	AUXILIAR DE PINTURA I
22	AUX PINTURA	AUXILIAR DE PINTURA
20	ELETRICISTA III	ELETRICISTA III
17	BORRACH I	BORRACHEIRO I
16	LANTERNEIRO II	LANTERNEIRO II
14	MECANICO I	MECANICO I
13	ELETRICISTA IV	ELETRICISTA IV
2432	AUX CUSTOS V	AUXILIAR DE CUSTOS V
2431	AUX CUSTOS III	AUXILIAR DE CUSTOS III
2427	ASS CONTABIL I	ASSISTENTE CONTABIL I
2414	AUX FINANC III	AUXILIAR FINANCEIRO III
2413	AUX COMERC II	AUXILIAR COMERCIAL II
2412	AUX COMERC I	AUXILIAR COMERCIAL I
2411	AUX COMERC IV	AUXILIAR COMERCIAL IV
2401	AUX COMPRAS II	AUXILIAR DE COMPRAS II
2400	AUX COMPRAS III	AUXILIAR DE COMPRRAS III
2399	AUX COMPRAS IV	AUXILIAR DE COMPRAS IV
2398	AUX COMPRAS V	AUXILIAR DE COMPRAS V
2397	AUX CONTABIL	AUXILIAR CONTABIL
2391	COZINHEIRA	COZINHEIRA
2390	AUX CUSTOS II	AUXILIAR DE CUSTOS II
2382	AUX FINANC IV	AUXILIAR FINANCEIRO IV
2381	AUX FINANC I	AUXILIAR FINANCEIRO I
2229	AUX TESOUR V	AUXILIAR DE TESOURARIA V
2228	AUX TESOUR IV	AUXILIAR TESOURAIA IV
2068	COORD CONTROL I	COORDENADOR CONTROLADORIA I
2065	ASSES DIRETORIA	ASSESSOR DIRETORIA
2059	ANL CONTROL IV	ANALISTA DE CONTROLADORIA IV
2053	ANL TI III	ANALISTA DE TI III
2025	COORD RH I	COORDENADOR DE RH I
830	AUX PESSOAL V	AUXILIAR PESSOAL V
829	AUX CONTABIL V	AUXILIAR CONTABIL V
828	AUX CONTABIL IV	AUXILIAR CONTABIL IV
827	ANL RH IV	ANALISTA RH IV
822	SUPERV CONTROL I	SUPERVISOR DE CONTROLADORIA I
820	ANL CONTABIL II	ANALISTA CONTABIL II
812	ASS FINANC II	ASSISTENTE FINANCEIRO II
811	ASS FINANC I	ASSISTENTE FINANCEIRO I
796	ANL CUSTOS II	ANALISTA DE CUSTOS II
794	AUX ENFERMAG I	AUXILIAR DE EMFERMAGEM I
582	AUX COMPRAS I	AUXILIAR DE COMPRAS I
580	GERENTE CUSTOS	GERENTE DE CUSTOS
559	AUX PESSOAL	AUXILIAR DE PESSOAL
530	AUX MEC PNEUMA I	AUXILIAR MECANICO PNEUMATICO I
518	AUDIT TESOUR II	AUDITOR DE TESOURARIA
515	ENG SEG TRABALHO	ENGENHEIRO DE SEGURANCA DO TRABALHO
507	AUX TESOUR II	AUXILIAR DE TESOURARIA II
500	GER UNIDADE	GERENTE DE UNIDADE
494	ADVOGADO PL I	ADVOGADO PLENO I
461	GER TRAFEGO	GERENTE DE TRAFEGO
456	AUX TST V	TECNICO DE SEGURANCA DO TRABALHO V AUXILIAR
420	AUX TESOU	AUXILIAR DE TESOURARIA
418	AUX CONTABIL I	AUXILIAR CONTABILIDADE I
408	ANL TI II	ANALISTA DE TI II
404	ASS JURIDICO II	ASSISTENTE JURIDICO II
396	ASSISTENTE RH II	ASSISTENTE DE RH II
391	ANL CUSTOS III	ANALISTA DE CUSTOS III
390	ANL CUSTOS I	ANALISTA DE CUSTOS I
389	AUX CUSTOS I	AUXILIAR DE CUSTOS I
383	AUX ADM V	AUXILIAR ADMINISTRATIVO V
372	AUX CONT MANUT I	AUXILIAR CONTROLADOR DE MANUTENCAO I
365	AUDIT TESOUR I	AUDITOR DE TESOURARIA I
363	AUX TESOUR III	AUXILIAR DE TESOURARIA III
361	COORD SERV MED I	COORDENADOR DE SERVICO MEDICO I
357	ANALISTA TI I	ANALISTA DE TI I
347	ANL TI	ANALISTA DE TI
343	ASS RH I	ASSISTENTE DE RH I
342	AUX PESSOAL IV	AUXILIAR DE PESSOAL IV
294	AUX PESSOAL III	AUXILIAR DE PESSOAL III
293	AUX PESSOAL II	AUXILIAR DE PESSOAL II
292	AUX FINANC II	AUXILIAR FINANCEIRO II
290	AUX CONTABIL III	AUXILIAR DE CONTABILIDADE III
287	ASS PESSOAL II	ASSISTENTE DE PESSOAL II
276	ANL RH III	ANALISTA DE RH III
275	ASS ADM II	ASSISTENTE ADMINISTRATIVO II
274	ANALISTA RH II	ANALISTA DE RH II
262	ASS TST II	TECNICO EM SEGURANCA DO TRABALHO ASSISTENTE II
233	SUPERV FINANC I	SUPERVISOR FINANCEIRO
224	SUPERV OPERAC I	SUPERVISOR DE OPERAÇÕES I
211	DIRETOR	DIRETOR
203	ADV JUNIOR	ADVOGADO JUNIOR
201	SECRETARIA	SECRETARIA
196	ELETRIC PREDIAL	ELETRICISTA
185	ANL CUSTOS V	ANALISTA DE CUSTOS V
180	AUX ENFERMAG	AUXILIAR DE ENFERMAGEM
173	MOTOBOY	MOTOBOY
168	RECEPCIONISTA	RECEPCIONISTA
159	ANL RH I	ANALISTA DE RH I
154	AUX ADM II	AUXILIAR ADMINISTRATIVO II
152	GER SUPRIMENTOS	GERENTE DE SUPRIMENTOS
120	GERENTE PESSOAL	GERENTE DEPARTAMENTO PESSOAL
114	MOT INSTRUTOR V	MOTORISTA INSTRUTOR V
111	MEDICO TRABALHO	MEDICO DO TRABALHO
108	ASS ADM III	ASSISTENTE ADMINISTRATIVO III
104	AUX ADM I	AUXILIAR ADMINISTRATIVO I
96	AUX CONTABIL II	AUXILIAR CONTABILIDADE II
65	GER MANUT	GERENTE DE MANUTENCAO
64	AUX ADM III	AUXILIAR ADMINISTRATIVO III
60	AUX ADM IV	AUXILIAR ADMINISTRATIVO IV
49	SERV EXTERNOS	SERVICOS EXTERNOS
37	GER RH	GERENTE DE RH
7	ASS ADM I	ASSISTENTE ADMINISTRATIVO I
5	AUX PESSOAL I	AUXILIAR PESSOAL I
4	ASS ADM IV	ASSISTENTE ADMINISTRATIVO IV
2435	BILHETEIRO III	BILHETEIRO III
2434	BILHETEIRO II	BILHETEIRO II
2433	BILHETEIRO I	BILHETEIRO I
2038	SUPERV FILIAL	SUPERVISOR FILIAL
2034	MOTORISTA INSTR	MOTORISTA  INSTRUTOR
2031	ENC OPERACIONAL	ENCARREGADO OPERACIONAL
2030	MOTORISTA CARRET	MOTORISTA CARRETEIRO
2020	ENC FILIAL	ENCARREGADO DE FILIAL
826	AUX TRAFEGO IV	AUXILIAR DE TRAFEGO IV
817	MOT CARGAS III	MOTORISTA CARGAS III
816	MOT CARGAS II	MOTORISTA CARGAS II
815	MOT CARGAS I	MOTORISTA CARGAS I
814	MOTORISTA CARGAS	MOTORISTA CARGAS
807	MOT RODOV I	MOTORISTA RODOVIARIO I
806	MOT RODOV II	MOTORISTA RODOVIARIO II
578	COORD BILHETE I	COORDENADOR DE BILHETERIA I
575	AGENTE VENDAS I	AGENTE DE VENDAS I
513	ENC ALMOX I	ENCARREGADO DE ALMOXARIFADO I
502	MANOBRISTA	MANOBRISTA
489	ALMOXARIFE V	ALMOXARIFE V
488	ALMOXARIFE IV	ALMOXARIFE IV
473	AUX TRAFEGO III	AUXILIAR DE TRAFEGO III
460	AUX ALMOXARIFADO	AUXILIAR DE ALMOXARIFADO
432	COORD TRAFEG III	COORDENADOR DE TRAFEGO III
431	COORD TRAFEG I	COORDENADOR DE TRAFEGO I
430	COORD TRAFEG II	COORDENADOR DE TRAFEGO II
421	AUX ALMOXARIFE I	AUXILIAR DE ALMOXARIFADO I
407	AUX TRAFEGO	AUXILIAR DE TRAFEGO
405	SUPERV TRAFEG II	SUPERVISOR DE TRAFEGO III
399	COORD TRAFEG IV	COODERNADOR DE TRAFEGO IV
351	AUX CARGAS	AUXILIAR DE CARGAS
350	EMISSOR DE FRETE	EMISSOR DE FRETE
345	COORD AUX VIAGEM	COORDENADOR AUXILIAR DE VIAGEM
312	PINTOR PREDIAL	PINTOR PREDIAL
282	MOTORISTA MICRO	MOTORISTA DE MICROONIBUS
273	CONF ENCOMEN III	CONFERENTE DE ENCOMENDAS
259	PEDREIRO B	PEDREIRO B
248	MOT RODOV III	MOTORISTA RODOVIARIO III
232	AGENTE VENDAS	AGENTE DE VENDAS
218	CONF ENCOMEN I	CONFERENTE DE ENCOMENDAS I
165	JARDINEIRO	JARDINEIRO
156	ENC ENCOMENDAS	ENCARREGADO DE ENCOMENDAS
155	CONF ENCOMEN II	CONFERENTE DE ENCOMENDAS II
146	FISCAL PLATAFOR	FISCAL DE PLATAFORMA
144	AUDIT OPERAC	AUDITOR DE OPERAÇÕES
139	AUX TRAFEGO II	AUXILIAR DE TRÁFEGO II
134	ALMOXARIFE	ALMOXARIFE
127	PORTEIRO	PORTEIRO
122	COORD BILHETERIA	COORDENADOR DE BILHETERIA
113	VIGILANTE	VIGILANTE
107	SUPERV TRAFEGO	SUPERVISOR DE TRAFEGO
86	ALMOXARIFE III	ALMOXARIFE III
78	MOTORISTA COMP	MOTORISTA COMPRADOR
73	DESPACHANTE	DESPACHANTE
70	MOTORISTA V LEVE	MOTORISTA DE VEICULO LEVE
67	AUX TRAFEGO I	AUXILIAR DE TRAFEGO I
54	COBRADOR	COBRADOR URBANO INTERIOR
53	MOTORISTA URB	MOTORISTA URBANO
46	PEDREIRO	PEDREIRO
43	ALMOXARIFE II	ALMOXARIFE II
21	FISCAL	FISCAL
12	BILHETEIRO	BILHETEIRO
11	MOTORISTA ROD	MOTORISTA RODOVIARIO
10	AUX DE VIAGEM	AUXILIAR DE VIAGEM
8	ENC TRAFEGO	ENCARREGADO TRAFEGO`;

async function main() {
  // Parse units
  const unitsLines = unitsRaw.split('\n').map(l => l.trim()).filter(l => l);
  const unitsData = [];
  const seenUnits = new Set();
  
  for (const line of unitsLines) {
    const parts = line.split('\t');
    if (parts.length >= 2) {
      let name = parts[1].trim();
      if (name === 'DESCRUÇÃO UNIDADE') continue;
      
      if (!seenUnits.has(name)) {
        seenUnits.add(name);
        unitsData.push({ name, is_adm_central: name === 'ADM CENTRAL' });
      }
    }
  }

  console.log(`Inserting ${unitsData.length} units...`);
  const { error: errUnits } = await supabase.from('units').upsert(unitsData, { onConflict: 'name', ignoreDuplicates: true });
  if (errUnits) console.error('Error inserting units:', errUnits.message);

  // Parse roles
  const rolesLines = rolesRaw.split('\n').map(l => l.trim()).filter(l => l);
  const rolesData = [];
  const seenRoles = new Set();
  
  for (const line of rolesLines) {
    const parts = line.split('\t');
    if (parts.length >= 2) {
      let name = parts.length >= 3 ? parts[2].trim() : parts[1].trim();
      if (name === 'DESCRIÇÃO COMPLETA FUNÇÃO') continue;
      
      if (!seenRoles.has(name)) {
        seenRoles.add(name);
        rolesData.push({ name });
      }
    }
  }

  console.log(`Inserting ${rolesData.length} roles...`);
  const batchSize = 100;
  for (let i = 0; i < rolesData.length; i += batchSize) {
    const batch = rolesData.slice(i, i + batchSize);
    const { error: errRoles } = await supabase.from('job_roles').upsert(batch, { onConflict: 'name', ignoreDuplicates: true });
    if (errRoles) console.error('Error inserting roles batch:', errRoles.message);
  }

  console.log('Done populating database!');
}

main();
