require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

const unitsRaw = `ADM CENTRAL
CAPELINHA
CEL FABRICIANO
DUVAL DE BARROS
ENCOMENDAS
EXPEDIÇÃO
INDÚSTRIA
IPATINGA
LAGOA SANTA
LAVRAS
MONTES CLAROS
NEVES MUNICIPAL
NOVA LIMA
SÃO MARCOS
TIMÓTEO
VARGINHA
VESPASIANO`;

const rolesRaw = `ADV JUNIOR
ADV JUNIOR I
ADV PLENO
ADVOGADO JR II
ADVOGADO PL II
ADVOGADO SR I
AGENTE ESTACAO
AGENTE VENDAS
ALMOXARIFE I
ALMOXARIFE II
ALMOXARIFE III
ALMOXARIFE IV
ALMOXARIFE V
ANL ADM II
ANL ALMOXARIFADO I
ANL ALMOXARIFADO II
ANL ALMOXARIFADO III
ANL ALMOXARIFADO IV
ANL ALMOXARIFADO V
ANL AMBIENT III
ANL COMERC II
ANL COMERC III
ANL COMP III
ANL COMPRAS I
ANL COMPRAS II
ANL CONTABIL I
ANL FINANC I
ANL FINANC II
ANL FISCAL I
ANL GARANTIA III
ANL GP² I
ANL GP² II
ANL GP² III
ANL GP² IV
ANL GP² V
ANL MANUTENCAO
ANL MARKETING I
ANL MARKETING II
ANL MARKETING III
ANL JURIDICO I
ANL OPERAC II
ANL OPERAC III
ANL OPERAC JR
ANL PESSOAL I
ANL PESSOAL II
ANL RH III
ANL SEG PATR III
ANL TEC ENF T II
ANL TESOUR I
ANL TESOUR II
ANL TESOUR V
ANL TESOURARIA I
ANL TI
ANL TI II
ANL TI III
ANL TST I
ANL TST II
ANL TST IV
ASS ADM I
ASS ADM II
ASS ADM IV
ASS BILHETAG I
ASS BILHETAG IV
ASS CONTABIL I
ASS CONTABIL II
ASS CONTABIL III
ASS CONTABIL IV
ASS CONTABIL V
ASS COMERC III
ASS DE ENCOM II
ASS FATURAM V
ASS FINANC I
ASS FINANC III
ASS FINANC V
ASS GP² I
ASS GP² III
ASS JURIDICO II
ASS JURIDICO III
ASS JURIDICO IV
ASS OPERAC I
ASS PESSOAL I
ASS PESSOAL III
ASS PESSOAL V
ASS PROJETOS I
ASS PROJETOS II
ASS PROJETOS III
ASS PROJETOS IV
ASS PROJETOS V
ASS SAC II
ASS TESOUR II
ASS TESOUR IV
ASS TESOUR V
ASS TESOURAR IV
ASS TI I
ASS TI II
ASS TI III
ASS TI IV
ASS TI V
ASS TST I
ASS TST II
ASS TST III
ASS TST IV
ASS TST V
ASS VENDAS I
ASS VENDAS II
ASSES IMPRENSA
ASSESSORA
AUDIT MANUT II
AUDITOR ALMOX II
AUX ADM I
AUX ADM IV
AUX ADM V
AUX ALMOXARIFADO
AUX BORRACH
AUX CAPOTARIA
AUX CARGAS
AUX COMERC IV
AUX COMERC V
AUX COMPRAS I
AUX COMPRAS II
AUX COMPRAS III
AUX COMPRAS IV
AUX COMPRAS V
AUX CONT MANUT
AUX CONTABIL II
AUX CONTABIL III
AUX CONTABIL IV
AUX CONTABIL V
AUX DE SAC I
AUX DE TI I
AUX DE VIAGEM
AUX ELETRICA
AUX FATURAM I
AUX FATURAM IV
AUX FATURAM V
ASS FINANC IV
AUX FINANC V
AUX FISCAL
AUX FISCAL V
AUX GP² I
AUX GP² II
AUX GP² III
AUX GP² IV
AUX GP² V
AUX JURIDICO I
AUX JURIDICO III
AUX JURIDICO IV
AUX LANTERN
AUX LANTERN I
AUX MANUTENCAO
AUX MEC IND
AUX MECANICA
AUX MONIT
AUX MONIT I
AUX MONIT II
AUX MONIT III
AUX MOLARIA
AUX OPERAC I
AUX OPERAC IV
AUX OPERAC V
AUX PESSOAL
AUX PESSOAL V
AUX PINTURA
AUX PINTURA I
AUX PLATAFORMA
AUX TESOU I
AUX TESOUR III
AUX TESOUR IV
AUX TESOUR V
AUX TORNEARIA
AUX TRAFEGO
AUX TRAFEGO I
AUX TRAFEGO II
AUX TRAFEGO III
AUX TST I
AUX TST IV
AUX TST V
BILHETEIRO
BILHETEIRO II
BILHETEIRO URB
BORRAC ALINH IV
BORRACH I
BORRACH II
BORRACH III
BORRACH IV
BORRACH V
CAPOTEIRO A
CAPOTEIRO II
CAPOTEIRO IV
CAPOTEIRO V
COBRADOR
COBRADOR URB
CONF ENCOMEN I
CONF ENCOMEN II
CONF ENCOMEN III
CONTR MANUT I
CONTR MANUT II
CONTR MANUT III
CONTR MANUT IV
COORD BILHETE I
COORD BILHETE IV
COORD CONTR III
COORD CONTROL I
COORD CUSTOS I
COORD ENCOM I
COORD MONIT
COORD MONIT I
COORD MONIT III
COORD TRAFEG
COORD TRAFEG I
COORD TRAFEG II
COORD TRAFEG III
COORD TRAFEG IV
COORD REGIONAL DE MANUT
COZINHEIRA
DESPACHANTE
ELETRIC PREDIAL
ELETRICISTA I
ELETRICISTA II
ELETRICISTA III
ELETRICISTA IV
ELETRICISTA V
EMISSOR DE FRETE
ENC ALMOX I
ENC CAPOTARIA I
ENC ELETRICA I
ENC ELETRICA II
ENC ENCOMENDAS
ENC GARAGEM I
ENC GARAGEM II
ENC LANTERN I
ENC LANTERN II
ENC MANUT B
ENC MANUT I
ENC MANUT II
ENC MANUT III
ENC SERV GER I
ENC SERV GER II
ENC TESOURARIA
ENC TRAFEGO
ENC USINAGEM II
ESTAGIÁRIO JURÍDICO
FISCAL
FISCAL PLATAFOR
FRENTISTA
GER CARGAS
GER COMPRAS
GER FINANCEIRO
GER GP² III
GER TRAINEE
GER UNIDADE
JOVEM APRENDIZ
LANTERNEIRO A
LANTERNEIRO I
LANTERNEIRO II
LANTERNEIRO III
LANTERNEIRO IV
LANTERNEIRO V
LUBRIFICADOR
MANOBRISTA
MEC INJECAO I
MEC INJECAO II
MEC MONTADOR I
MEC MONTADOR II
MEC MONTADOR III
MEC PNEUMAT IV
MEC PNEUMAT V
MECANICO A
MECANICO I
MECANICO II
MECANICO III
MECANICO IND II
MECANICO IND III
MECANICO IND IV
MECANICO IND V
MECANICO IV
MECANICO V
MEDICO TRABALHO
MOLEIRO I
MOLEIRO III
MOLEIRO IV
MOLEIRO V
MOT INSTRUTOR V
MOT RODOV I
MOT RODOV II
MOTOBOY
MOTORISTA CARGAS
MOTORISTA CARRETEIRO
MOTORISTA INSTR
MOTORISTA MICRO
MOTORISTA VEICULOS LEVE
PEDREIRO
PINTOR I
PINTOR II
PINTOR III
PINTOR IV
PINTOR PREDIAL
PINTOR V
PORTEIRO
RECEPCIONISTA
REPOSITOR OLEO
SECRETARIA
SEGURANCA
SERV GERAIS
SERVENT PEDREIRO
SOLDADOR IV
SUPERV CONTAB II
SUPERV CONTR II
SUPERV DESENV I
SUPERV FATUR III
SUPERV FINAN III
SUPERV FINANC I
SUPERV GP2 I
SUPERV MANUT JR
SUPERV MANUT PL
SUPERV MANUT SR
SUPERV OPERAC II
SUPERV PESSO III
SUPERV TRAFE III
SUPERV TRAFEG I
SUPERV TRAFEG II
SUPERV TRAFEGO
TEC ENF TRAB I
TESOUREIRO I
TESOUREIRO III
TORNEIRO MEC II
TORNEIRO MEC III
TORNEIRO MEC IV
TORNEIRO MEC V
ZELADOR
TEC EDIFICACOES
ASS SINISTRO V
COORD MANUTENCAO
ANL DE MANUTENCAO
ASS COMPRAS V
ASS JURIDICO I`;

async function main() {
  const unitsLines = unitsRaw.split('\n').map(l => l.trim()).filter(l => l);
  const unitsData = unitsLines.map(name => ({
    name,
    is_adm_central: name === 'ADM CENTRAL'
  }));

  console.log(`Inserting ${unitsData.length} units...`);
  const { error: errUnits } = await supabase.from('units').upsert(unitsData, { onConflict: 'name', ignoreDuplicates: true });
  if (errUnits) console.error('Error inserting units:', errUnits.message);

  const rolesLines = rolesRaw.split('\n').map(l => l.trim()).filter(l => l);
  const rolesData = rolesLines.map(name => ({ name }));

  console.log(`Inserting ${rolesData.length} roles...`);
  const batchSize = 100;
  for (let i = 0; i < rolesData.length; i += batchSize) {
    const batch = rolesData.slice(i, i + batchSize);
    const { error: errRoles } = await supabase.from('job_roles').upsert(batch, { onConflict: 'name', ignoreDuplicates: true });
    if (errRoles) console.error('Error inserting roles batch:', errRoles.message);
  }

  console.log('Done populating database!');
}

main();
